import { ItemNode, Tier } from '../item-node';

export const items: ItemNode[] = [
  { id: 'alpha-jakyl', displayName: 'Alpha Jakyl', type: 'cargo', tier: Tier.T0 },
  { id: 'argent-ore-chunk', displayName: 'Argent Ore Chunk', type: 'cargo', tier: Tier.T0 },
  { id: 'auric-ore-chunk', displayName: 'Auric Ore Chunk', type: 'cargo', tier: Tier.T0 },
  { id: 'faint-energy', displayName: 'Faint Energy', type: 'cargo', tier: Tier.T0 },
  { id: 'hexite-capsule', displayName: 'Hexite Capsule', type: 'cargo', tier: Tier.T0 },
  { id: 'jakyl', displayName: 'Jakyl', type: 'cargo', tier: Tier.T0 },
  { id: 'overwhelming-energy', displayName: 'Overwhelming Energy', type: 'cargo', tier: Tier.T0 },
  { id: 'umbura', displayName: 'Umbura', type: 'cargo', tier: Tier.T0 },
  { id: 'beginners-stone-carving-package', displayName: 'Beginner\'s Stone Carving Package', type: 'cargo', tier: Tier.T1 },
  { id: 'bottomless-sack-of-hex-coins', displayName: 'Bottomless Sack of Hex Coins', type: 'cargo', tier: Tier.T1 },
  { id: 'cheaters-boat', displayName: 'Cheater\'s Boat', type: 'cargo', tier: Tier.T1 },
  { id: 'fair-sack-of-hex-coins', displayName: 'Fair Sack of Hex Coins', type: 'cargo', tier: Tier.T1 },
  { id: 'ferralith-frames', displayName: 'Ferralith Frames', type: 'cargo', tier: Tier.T1 },
  { id: 'ferralith-ingot-package', displayName: 'Ferralith Ingot Package', type: 'cargo', tier: Tier.T1 },
  { id: 'ferralith-ore-chunk', displayName: 'Ferralith Ore Chunk', type: 'cargo', tier: Tier.T1 },
  { id: 'fishers-boat', displayName: 'Fisher\'s Boat', type: 'cargo', tier: Tier.T1 },
  { id: 'flint-chunk', displayName: 'Flint Chunk', type: 'cargo', tier: Tier.T1 },
  { id: 'large-sack-of-hex-coins', displayName: 'Large Sack of Hex Coins', type: 'cargo', tier: Tier.T1 },
  { id: 'oceancrest-marlin', displayName: 'Oceancrest Marlin', type: 'cargo', tier: Tier.T1 },
  { id: 'refined-ferralith-ingot-package', displayName: 'Refined Ferralith Ingot Package', type: 'cargo', tier: Tier.T1 },
  { id: 'refined-rough-brick-package', displayName: 'Refined Rough Brick Package', type: 'cargo', tier: Tier.T1 },
  { id: 'refined-rough-cloth-package', displayName: 'Refined Rough Cloth Package', type: 'cargo', tier: Tier.T1 },
  { id: 'refined-rough-leather-package', displayName: 'Refined Rough Leather Package', type: 'cargo', tier: Tier.T1 },
  { id: 'refined-rough-wood-plank-package', displayName: 'Refined Rough Wood Plank Package', type: 'cargo', tier: Tier.T1 },
  { id: 'rideable-deer', displayName: 'Rideable Deer', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-brick-package', displayName: 'Rough Brick Package', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-brick-slab', displayName: 'Rough Brick Slab', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-cart-material-pack', displayName: 'Rough Cart Material Pack', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-chemical-supply-pack', displayName: 'Rough Chemical Supply Pack', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-cloth-package', displayName: 'Rough Cloth Package', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-cloth-tarp', displayName: 'Rough Cloth Tarp', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-clothing-materials-pack', displayName: 'Rough Clothing Materials Pack', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-construction-materials-pack', displayName: 'Rough Construction Materials Pack', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-geode', displayName: 'Rough Geode', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-large-cart-material-pack', displayName: 'Rough Large Cart Material Pack', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-leather-package', displayName: 'Rough Leather Package', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-leather-sheeting', displayName: 'Rough Leather Sheeting', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-plant-roots', displayName: 'Rough Plant Roots', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-raft-material-pack', displayName: 'Rough Raft Material Pack', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-rock-package', displayName: 'Rough Rock Package', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-skiff-material-pack', displayName: 'Rough Skiff Material Pack', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-stone-chunk', displayName: 'Rough Stone Chunk', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-timber', displayName: 'Rough Timber', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-wood-log-package', displayName: 'Rough Wood Log Package', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-wood-plank-package', displayName: 'Rough Wood Plank Package', type: 'cargo', tier: Tier.T1 },
  { id: 'rough-wood-trunk', displayName: 'Rough Wood Trunk', type: 'cargo', tier: Tier.T1 },
  { id: 'sagi-bird', displayName: 'Sagi Bird', type: 'cargo', tier: Tier.T1 },
  { id: 'small-sack-of-hex-coins', displayName: 'Small Sack of Hex Coins', type: 'cargo', tier: Tier.T1 },
  { id: 'improved-skiff-material-pack', displayName: 'Improved Skiff Material Pack', type: 'cargo', tier: Tier.T2 },
  { id: 'novice-stone-carving-package', displayName: 'Novice Stone Carving Package', type: 'cargo', tier: Tier.T2 },
  { id: 'nubi-goat', displayName: 'Nubi Goat', type: 'cargo', tier: Tier.T2 },
  { id: 'pyrelite-frames', displayName: 'Pyrelite Frames', type: 'cargo', tier: Tier.T2 },
  { id: 'pyrelite-ingot-package', displayName: 'Pyrelite Ingot Package', type: 'cargo', tier: Tier.T2 },
  { id: 'pyrelite-ore-chunk', displayName: 'Pyrelite Ore Chunk', type: 'cargo', tier: Tier.T2 },
  { id: 'refined-pyrelite-ingot-package', displayName: 'Refined Pyrelite Ingot Package', type: 'cargo', tier: Tier.T2 },
  { id: 'refined-simple-brick-package', displayName: 'Refined Simple Brick Package', type: 'cargo', tier: Tier.T2 },
  { id: 'refined-simple-cloth-package', displayName: 'Refined Simple Cloth Package', type: 'cargo', tier: Tier.T2 },
  { id: 'refined-simple-leather-package', displayName: 'Refined Simple Leather Package', type: 'cargo', tier: Tier.T2 },
  { id: 'refined-simple-wood-plank-package', displayName: 'Refined Simple Wood Plank Package', type: 'cargo', tier: Tier.T2 },
  { id: 'serpentfish', displayName: 'Serpentfish', type: 'cargo', tier: Tier.T2 },
  { id: 'simple-brick-package', displayName: 'Simple Brick Package', type: 'cargo', tier: Tier.T2 },
  { id: 'simple-brick-slab', displayName: 'Simple Brick Slab', type: 'cargo', tier: Tier.T2 },
  { id: 'simple-chemical-supply-pack', displayName: 'Simple Chemical Supply Pack', type: 'cargo', tier: Tier.T2 },
  { id: 'simple-cloth-package', displayName: 'Simple Cloth Package', type: 'cargo', tier: Tier.T2 },
  { id: 'simple-cloth-tarp', displayName: 'Simple Cloth Tarp', type: 'cargo', tier: Tier.T2 },
  { id: 'simple-clothing-materials-pack', displayName: 'Simple Clothing Materials Pack', type: 'cargo', tier: Tier.T2 },
  { id: 'simple-construction-materials-pack', displayName: 'Simple Construction Materials Pack', type: 'cargo', tier: Tier.T2 },
  { id: 'simple-geode', displayName: 'Simple Geode', type: 'cargo', tier: Tier.T2 },
  { id: 'simple-leather-package', displayName: 'Simple Leather Package', type: 'cargo', tier: Tier.T2 },
  { id: 'simple-leather-sheeting', displayName: 'Simple Leather Sheeting', type: 'cargo', tier: Tier.T2 },
  { id: 'simple-plant-roots', displayName: 'Simple Plant Roots', type: 'cargo', tier: Tier.T2 },
  { id: 'simple-rock-package', displayName: 'Simple Rock Package', type: 'cargo', tier: Tier.T2 },
  { id: 'simple-stone-chunk', displayName: 'Simple Stone Chunk', type: 'cargo', tier: Tier.T2 },
  { id: 'simple-timber', displayName: 'Simple Timber', type: 'cargo', tier: Tier.T2 },
  { id: 'simple-wood-log-package', displayName: 'Simple Wood Log Package', type: 'cargo', tier: Tier.T2 },
  { id: 'simple-wood-plank-package', displayName: 'Simple Wood Plank Package', type: 'cargo', tier: Tier.T2 },
  { id: 'simple-wood-trunk', displayName: 'Simple Wood Trunk', type: 'cargo', tier: Tier.T2 },
  { id: 'advanced-skiff-material-pack', displayName: 'Advanced Skiff Material Pack', type: 'cargo', tier: Tier.T3 },
  { id: 'emarium-frames', displayName: 'Emarium Frames', type: 'cargo', tier: Tier.T3 },
  { id: 'emarium-ingot-package', displayName: 'Emarium Ingot Package', type: 'cargo', tier: Tier.T3 },
  { id: 'emarium-ore-chunk', displayName: 'Emarium Ore Chunk', type: 'cargo', tier: Tier.T3 },
  { id: 'essential-stone-carving-package', displayName: 'Essential Stone Carving Package', type: 'cargo', tier: Tier.T3 },
  { id: 'female-cervus', displayName: 'Female Cervus', type: 'cargo', tier: Tier.T3 },
  { id: 'infused-chemical-supply-pack', displayName: 'Infused Chemical Supply Pack', type: 'cargo', tier: Tier.T3 },
  { id: 'male-cervus', displayName: 'Male Cervus', type: 'cargo', tier: Tier.T3 },
  { id: 'refined-emarium-ingot-package', displayName: 'Refined Emarium Ingot Package', type: 'cargo', tier: Tier.T3 },
  { id: 'refined-sturdy-brick-package', displayName: 'Refined Sturdy Brick Package', type: 'cargo', tier: Tier.T3 },
  { id: 'refined-sturdy-cloth-package', displayName: 'Refined Sturdy Cloth Package', type: 'cargo', tier: Tier.T3 },
  { id: 'refined-sturdy-leather-package', displayName: 'Refined Sturdy Leather Package', type: 'cargo', tier: Tier.T3 },
  { id: 'refined-sturdy-wood-plank-package', displayName: 'Refined Sturdy Wood Plank Package', type: 'cargo', tier: Tier.T3 },
  { id: 'sturdy-brick-package', displayName: 'Sturdy Brick Package', type: 'cargo', tier: Tier.T3 },
  { id: 'sturdy-brick-slab', displayName: 'Sturdy Brick Slab', type: 'cargo', tier: Tier.T3 },
  { id: 'sturdy-cloth-package', displayName: 'Sturdy Cloth Package', type: 'cargo', tier: Tier.T3 },
  { id: 'sturdy-cloth-tarp', displayName: 'Sturdy Cloth Tarp', type: 'cargo', tier: Tier.T3 },
  { id: 'sturdy-clothing-materials-pack', displayName: 'Sturdy Clothing Materials Pack', type: 'cargo', tier: Tier.T3 },
  { id: 'sturdy-construction-materials-pack', displayName: 'Sturdy Construction Materials Pack', type: 'cargo', tier: Tier.T3 },
  { id: 'sturdy-geode', displayName: 'Sturdy Geode', type: 'cargo', tier: Tier.T3 },
  { id: 'sturdy-leather-package', displayName: 'Sturdy Leather Package', type: 'cargo', tier: Tier.T3 },
  { id: 'sturdy-leather-sheeting', displayName: 'Sturdy Leather Sheeting', type: 'cargo', tier: Tier.T3 },
  { id: 'sturdy-plant-roots', displayName: 'Sturdy Plant Roots', type: 'cargo', tier: Tier.T3 },
  { id: 'sturdy-rock-package', displayName: 'Sturdy Rock Package', type: 'cargo', tier: Tier.T3 },
  { id: 'sturdy-stone-chunk', displayName: 'Sturdy Stone Chunk', type: 'cargo', tier: Tier.T3 },
  { id: 'sturdy-timber', displayName: 'Sturdy Timber', type: 'cargo', tier: Tier.T3 },
  { id: 'sturdy-wood-log-package', displayName: 'Sturdy Wood Log Package', type: 'cargo', tier: Tier.T3 },
  { id: 'sturdy-wood-plank-package', displayName: 'Sturdy Wood Plank Package', type: 'cargo', tier: Tier.T3 },
  { id: 'sturdy-wood-trunk', displayName: 'Sturdy Wood Trunk', type: 'cargo', tier: Tier.T3 },
  { id: 'wavecrest-eel', displayName: 'Wavecrest Eel', type: 'cargo', tier: Tier.T3 },
  { id: 'ardea', displayName: 'Ardea', type: 'cargo', tier: Tier.T4 },
  { id: 'elenvar-frames', displayName: 'Elenvar Frames', type: 'cargo', tier: Tier.T4 },
  { id: 'elenvar-ingot-package', displayName: 'Elenvar Ingot Package', type: 'cargo', tier: Tier.T4 },
  { id: 'elenvar-ore-chunk', displayName: 'Elenvar Ore Chunk', type: 'cargo', tier: Tier.T4 },
  { id: 'experts-skiff-material-pack', displayName: 'Expert\'s Skiff Material Pack', type: 'cargo', tier: Tier.T4 },
  { id: 'female-scrofa', displayName: 'Female Scrofa', type: 'cargo', tier: Tier.T4 },
  { id: 'fine-brick-package', displayName: 'Fine Brick Package', type: 'cargo', tier: Tier.T4 },
  { id: 'fine-brick-slab', displayName: 'Fine Brick Slab', type: 'cargo', tier: Tier.T4 },
  { id: 'fine-chemical-supply-pack', displayName: 'Fine Chemical Supply Pack', type: 'cargo', tier: Tier.T4 },
  { id: 'fine-cloth-package', displayName: 'Fine Cloth Package', type: 'cargo', tier: Tier.T4 },
  { id: 'fine-cloth-tarp', displayName: 'Fine Cloth Tarp', type: 'cargo', tier: Tier.T4 },
  { id: 'fine-clothing-materials-pack', displayName: 'Fine Clothing Materials Pack', type: 'cargo', tier: Tier.T4 },
  { id: 'fine-construction-materials-pack', displayName: 'Fine Construction Materials Pack', type: 'cargo', tier: Tier.T4 },
  { id: 'fine-geode', displayName: 'Fine Geode', type: 'cargo', tier: Tier.T4 },
  { id: 'fine-leather-package', displayName: 'Fine Leather Package', type: 'cargo', tier: Tier.T4 },
  { id: 'fine-leather-sheeting', displayName: 'Fine Leather Sheeting', type: 'cargo', tier: Tier.T4 },
  { id: 'fine-plant-roots', displayName: 'Fine Plant Roots', type: 'cargo', tier: Tier.T4 },
  { id: 'fine-rock-package', displayName: 'Fine Rock Package', type: 'cargo', tier: Tier.T4 },
  { id: 'fine-stone-chunk', displayName: 'Fine Stone Chunk', type: 'cargo', tier: Tier.T4 },
  { id: 'fine-timber', displayName: 'Fine Timber', type: 'cargo', tier: Tier.T4 },
  { id: 'fine-trunk', displayName: 'Fine Trunk', type: 'cargo', tier: Tier.T4 },
  { id: 'fine-wood-log-package', displayName: 'Fine Wood Log Package', type: 'cargo', tier: Tier.T4 },
  { id: 'fine-wood-plank-package', displayName: 'Fine Wood Plank Package', type: 'cargo', tier: Tier.T4 },
  { id: 'male-scrofa', displayName: 'Male Scrofa', type: 'cargo', tier: Tier.T4 },
  { id: 'proficient-stone-carving-package', displayName: 'Proficient Stone Carving Package', type: 'cargo', tier: Tier.T4 },
  { id: 'rangifer', displayName: 'Rangifer', type: 'cargo', tier: Tier.T4 },
  { id: 'refined-elenvar-ingot-package', displayName: 'Refined Elenvar Ingot Package', type: 'cargo', tier: Tier.T4 },
  { id: 'refined-fine-brick-package', displayName: 'Refined Fine Brick Package', type: 'cargo', tier: Tier.T4 },
  { id: 'refined-fine-cloth-package', displayName: 'Refined Fine Cloth Package', type: 'cargo', tier: Tier.T4 },
  { id: 'refined-fine-leather-package', displayName: 'Refined Fine Leather Package', type: 'cargo', tier: Tier.T4 },
  { id: 'refined-fine-wood-plank-package', displayName: 'Refined Fine Wood Plank Package', type: 'cargo', tier: Tier.T4 },
  { id: 'seastorm-tuna', displayName: 'Seastorm Tuna', type: 'cargo', tier: Tier.T4 },
  { id: 'advanced-stone-carving-package', displayName: 'Advanced Stone Carving Package', type: 'cargo', tier: Tier.T5 },
  { id: 'azure-shark', displayName: 'Azure Shark', type: 'cargo', tier: Tier.T5 },
  { id: 'dromai', displayName: 'Dromai', type: 'cargo', tier: Tier.T5 },
  { id: 'exquisite-brick-package', displayName: 'Exquisite Brick Package', type: 'cargo', tier: Tier.T5 },
  { id: 'exquisite-brick-slab', displayName: 'Exquisite Brick Slab', type: 'cargo', tier: Tier.T5 },
  { id: 'exquisite-chemical-supply-pack', displayName: 'Exquisite Chemical Supply Pack', type: 'cargo', tier: Tier.T5 },
  { id: 'exquisite-cloth-package', displayName: 'Exquisite Cloth Package', type: 'cargo', tier: Tier.T5 },
  { id: 'exquisite-cloth-tarp', displayName: 'Exquisite Cloth Tarp', type: 'cargo', tier: Tier.T5 },
  { id: 'exquisite-clothing-materials-pack', displayName: 'Exquisite Clothing Materials Pack', type: 'cargo', tier: Tier.T5 },
  { id: 'exquisite-construction-materials-pack', displayName: 'Exquisite Construction Materials Pack', type: 'cargo', tier: Tier.T5 },
  { id: 'exquisite-geode', displayName: 'Exquisite Geode', type: 'cargo', tier: Tier.T5 },
  { id: 'exquisite-leather-package', displayName: 'Exquisite Leather Package', type: 'cargo', tier: Tier.T5 },
  { id: 'exquisite-leather-sheeting', displayName: 'Exquisite Leather Sheeting', type: 'cargo', tier: Tier.T5 },
  { id: 'exquisite-plant-roots', displayName: 'Exquisite Plant Roots', type: 'cargo', tier: Tier.T5 },
  { id: 'exquisite-rock-package', displayName: 'Exquisite Rock Package', type: 'cargo', tier: Tier.T5 },
  { id: 'exquisite-stone-chunk', displayName: 'Exquisite Stone Chunk', type: 'cargo', tier: Tier.T5 },
  { id: 'exquisite-timber', displayName: 'Exquisite Timber', type: 'cargo', tier: Tier.T5 },
  { id: 'exquisite-trunk', displayName: 'Exquisite Trunk', type: 'cargo', tier: Tier.T5 },
  { id: 'exquisite-wood-log-package', displayName: 'Exquisite Wood Log Package', type: 'cargo', tier: Tier.T5 },
  { id: 'exquisite-wood-plank-package', displayName: 'Exquisite Wood Plank Package', type: 'cargo', tier: Tier.T5 },
  { id: 'luminite-frames', displayName: 'Luminite Frames', type: 'cargo', tier: Tier.T5 },
  { id: 'luminite-ingot-package', displayName: 'Luminite Ingot Package', type: 'cargo', tier: Tier.T5 },
  { id: 'luminite-ore-chunk', displayName: 'Luminite Ore Chunk', type: 'cargo', tier: Tier.T5 },
  { id: 'masterful-skiff-material-pack', displayName: 'Masterful Skiff Material Pack', type: 'cargo', tier: Tier.T5 },
  { id: 'plains-ox', displayName: 'Plains Ox', type: 'cargo', tier: Tier.T5 },
  { id: 'refined-exquisite-brick-package', displayName: 'Refined Exquisite Brick Package', type: 'cargo', tier: Tier.T5 },
  { id: 'refined-exquisite-cloth-package', displayName: 'Refined Exquisite Cloth Package', type: 'cargo', tier: Tier.T5 },
  { id: 'refined-exquisite-leather-package', displayName: 'Refined Exquisite Leather Package', type: 'cargo', tier: Tier.T5 },
  { id: 'refined-exquisite-wood-plank-package', displayName: 'Refined Exquisite Wood Plank Package', type: 'cargo', tier: Tier.T5 },
  { id: 'refined-luminite-ingot-package', displayName: 'Refined Luminite Ingot Package', type: 'cargo', tier: Tier.T5 },
  { id: 'abyssal-swordfish', displayName: 'Abyssal Swordfish', type: 'cargo', tier: Tier.T6 },
  { id: 'comprehensive-stone-carving-package', displayName: 'Comprehensive Stone Carving Package', type: 'cargo', tier: Tier.T6 },
  { id: 'fishers-boat-material-pack', displayName: 'Fisher\'s Boat Material Pack', type: 'cargo', tier: Tier.T6 },
  { id: 'peerless-brick-package', displayName: 'Peerless Brick Package', type: 'cargo', tier: Tier.T6 },
  { id: 'peerless-brick-slab', displayName: 'Peerless Brick Slab', type: 'cargo', tier: Tier.T6 },
  { id: 'peerless-chemical-supply-pack', displayName: 'Peerless Chemical Supply Pack', type: 'cargo', tier: Tier.T6 },
  { id: 'peerless-cloth-package', displayName: 'Peerless Cloth Package', type: 'cargo', tier: Tier.T6 },
  { id: 'peerless-cloth-tarp', displayName: 'Peerless Cloth Tarp', type: 'cargo', tier: Tier.T6 },
  { id: 'peerless-clothing-materials-pack', displayName: 'Peerless Clothing Materials Pack', type: 'cargo', tier: Tier.T6 },
  { id: 'peerless-construction-materials-pack', displayName: 'Peerless Construction Materials Pack', type: 'cargo', tier: Tier.T6 },
  { id: 'peerless-geode', displayName: 'Peerless Geode', type: 'cargo', tier: Tier.T6 },
  { id: 'peerless-leather-package', displayName: 'Peerless Leather Package', type: 'cargo', tier: Tier.T6 },
  { id: 'peerless-leather-sheeting', displayName: 'Peerless Leather Sheeting', type: 'cargo', tier: Tier.T6 },
  { id: 'peerless-plant-roots', displayName: 'Peerless Plant Roots', type: 'cargo', tier: Tier.T6 },
  { id: 'peerless-rock-package', displayName: 'Peerless Rock Package', type: 'cargo', tier: Tier.T6 },
  { id: 'peerless-stone-chunk', displayName: 'Peerless Stone Chunk', type: 'cargo', tier: Tier.T6 },
  { id: 'peerless-timber', displayName: 'Peerless Timber', type: 'cargo', tier: Tier.T6 },
  { id: 'peerless-trunk', displayName: 'Peerless Trunk', type: 'cargo', tier: Tier.T6 },
  { id: 'peerless-wood-log-package', displayName: 'Peerless Wood Log Package', type: 'cargo', tier: Tier.T6 },
  { id: 'peerless-wood-plank-package', displayName: 'Peerless Wood Plank Package', type: 'cargo', tier: Tier.T6 },
  { id: 'rathium-frames', displayName: 'Rathium Frames', type: 'cargo', tier: Tier.T6 },
  { id: 'rathium-ingot-package', displayName: 'Rathium Ingot Package', type: 'cargo', tier: Tier.T6 },
  { id: 'rathium-ore-chunk', displayName: 'Rathium Ore Chunk', type: 'cargo', tier: Tier.T6 },
  { id: 'refined-peerless-brick-package', displayName: 'Refined Peerless Brick Package', type: 'cargo', tier: Tier.T6 },
  { id: 'refined-peerless-cloth-package', displayName: 'Refined Peerless Cloth Package', type: 'cargo', tier: Tier.T6 },
  { id: 'refined-peerless-leather-package', displayName: 'Refined Peerless Leather Package', type: 'cargo', tier: Tier.T6 },
  { id: 'refined-peerless-wood-plank-package', displayName: 'Refined Peerless Wood Plank Package', type: 'cargo', tier: Tier.T6 },
  { id: 'refined-rathium-ingot-package', displayName: 'Refined Rathium Ingot Package', type: 'cargo', tier: Tier.T6 },
  { id: 'yagi', displayName: 'Yagi', type: 'cargo', tier: Tier.T6 },
  { id: 'aurumite-frames', displayName: 'Aurumite Frames', type: 'cargo', tier: Tier.T7 },
  { id: 'aurumite-ingot-package', displayName: 'Aurumite Ingot Package', type: 'cargo', tier: Tier.T7 },
  { id: 'aurumite-ore-chunk', displayName: 'Aurumite Ore Chunk', type: 'cargo', tier: Tier.T7 },
  { id: 'jungle-terrorbird', displayName: 'Jungle Terrorbird', type: 'cargo', tier: Tier.T7 },
  { id: 'ornate-brick-package', displayName: 'Ornate Brick Package', type: 'cargo', tier: Tier.T7 },
  { id: 'ornate-brick-slab', displayName: 'Ornate Brick Slab', type: 'cargo', tier: Tier.T7 },
  { id: 'ornate-chemical-supply-pack', displayName: 'Ornate Chemical Supply Pack', type: 'cargo', tier: Tier.T7 },
  { id: 'ornate-cloth-package', displayName: 'Ornate Cloth Package', type: 'cargo', tier: Tier.T7 },
  { id: 'ornate-cloth-tarp', displayName: 'Ornate Cloth Tarp', type: 'cargo', tier: Tier.T7 },
  { id: 'ornate-clothing-materials-pack', displayName: 'Ornate Clothing Materials Pack', type: 'cargo', tier: Tier.T7 },
  { id: 'ornate-geode', displayName: 'Ornate Geode', type: 'cargo', tier: Tier.T7 },
  { id: 'ornate-leather-package', displayName: 'Ornate Leather Package', type: 'cargo', tier: Tier.T7 },
  { id: 'ornate-leather-sheeting', displayName: 'Ornate Leather Sheeting', type: 'cargo', tier: Tier.T7 },
  { id: 'ornate-plant-roots', displayName: 'Ornate Plant Roots', type: 'cargo', tier: Tier.T7 },
  { id: 'ornate-rock-package', displayName: 'Ornate Rock Package', type: 'cargo', tier: Tier.T7 },
  { id: 'ornate-stone-carving-package', displayName: 'Ornate Stone Carving Package', type: 'cargo', tier: Tier.T7 },
  { id: 'ornate-stone-chunk', displayName: 'Ornate Stone Chunk', type: 'cargo', tier: Tier.T7 },
  { id: 'ornate-timber', displayName: 'Ornate Timber', type: 'cargo', tier: Tier.T7 },
  { id: 'ornate-trunk', displayName: 'Ornate Trunk', type: 'cargo', tier: Tier.T7 },
  { id: 'ornate-wood-log-package', displayName: 'Ornate Wood Log Package', type: 'cargo', tier: Tier.T7 },
  { id: 'ornate-wood-plank-package', displayName: 'Ornate Wood Plank Package', type: 'cargo', tier: Tier.T7 },
  { id: 'refined-aurumite-ingot-package', displayName: 'Refined Aurumite Ingot Package', type: 'cargo', tier: Tier.T7 },
  { id: 'refined-ornate-brick-package', displayName: 'Refined Ornate Brick Package', type: 'cargo', tier: Tier.T7 },
  { id: 'refined-ornate-cloth-package', displayName: 'Refined Ornate Cloth Package', type: 'cargo', tier: Tier.T7 },
  { id: 'refined-ornate-leather-package', displayName: 'Refined Ornate Leather Package', type: 'cargo', tier: Tier.T7 },
  { id: 'refined-ornate-wood-plank-package', displayName: 'Refined Ornate Wood Plank Package', type: 'cargo', tier: Tier.T7 },
  { id: 'tidebreaker-barracuda', displayName: 'Tidebreaker Barracuda', type: 'cargo', tier: Tier.T7 },
  { id: 'tier-7-animal', displayName: 'Tier 7 Animal', type: 'cargo', tier: Tier.T7 },
  { id: 'celestium-frames', displayName: 'Celestium Frames', type: 'cargo', tier: Tier.T8 },
  { id: 'celestium-ingot-package', displayName: 'Celestium Ingot Package', type: 'cargo', tier: Tier.T8 },
  { id: 'celestium-ore-chunk', displayName: 'Celestium Ore Chunk', type: 'cargo', tier: Tier.T8 },
  { id: 'elder-scrofa', displayName: 'Elder Scrofa', type: 'cargo', tier: Tier.T8 },
  { id: 'mysterious-anglerfish', displayName: 'Mysterious Anglerfish', type: 'cargo', tier: Tier.T8 },
  { id: 'pristine-brick-package', displayName: 'Pristine Brick Package', type: 'cargo', tier: Tier.T8 },
  { id: 'pristine-brick-slab', displayName: 'Pristine Brick Slab', type: 'cargo', tier: Tier.T8 },
  { id: 'pristine-chemical-supply-pack', displayName: 'Pristine Chemical Supply Pack', type: 'cargo', tier: Tier.T8 },
  { id: 'pristine-cloth-package', displayName: 'Pristine Cloth Package', type: 'cargo', tier: Tier.T8 },
  { id: 'pristine-cloth-tarp', displayName: 'Pristine Cloth Tarp', type: 'cargo', tier: Tier.T8 },
  { id: 'pristine-clothing-materials-pack', displayName: 'Pristine Clothing Materials Pack', type: 'cargo', tier: Tier.T8 },
  { id: 'pristine-geode', displayName: 'Pristine Geode', type: 'cargo', tier: Tier.T8 },
  { id: 'pristine-leather-package', displayName: 'Pristine Leather Package', type: 'cargo', tier: Tier.T8 },
  { id: 'pristine-leather-sheeting', displayName: 'Pristine Leather Sheeting', type: 'cargo', tier: Tier.T8 },
  { id: 'pristine-plant-roots', displayName: 'Pristine Plant Roots', type: 'cargo', tier: Tier.T8 },
  { id: 'pristine-rock-package', displayName: 'Pristine Rock Package', type: 'cargo', tier: Tier.T8 },
  { id: 'pristine-stone-carving-package', displayName: 'Pristine Stone Carving Package', type: 'cargo', tier: Tier.T8 },
  { id: 'pristine-stone-chunk', displayName: 'Pristine Stone Chunk', type: 'cargo', tier: Tier.T8 },
  { id: 'pristine-timber', displayName: 'Pristine Timber', type: 'cargo', tier: Tier.T8 },
  { id: 'pristine-trunk', displayName: 'Pristine Trunk', type: 'cargo', tier: Tier.T8 },
  { id: 'pristine-wood-log-package', displayName: 'Pristine Wood Log Package', type: 'cargo', tier: Tier.T8 },
  { id: 'pristine-wood-plank-package', displayName: 'Pristine Wood Plank Package', type: 'cargo', tier: Tier.T8 },
  { id: 'refined-celestium-ingot-package', displayName: 'Refined Celestium Ingot Package', type: 'cargo', tier: Tier.T8 },
  { id: 'refined-pristine-brick-package', displayName: 'Refined Pristine Brick Package', type: 'cargo', tier: Tier.T8 },
  { id: 'refined-pristine-cloth-package', displayName: 'Refined Pristine Cloth Package', type: 'cargo', tier: Tier.T8 },
  { id: 'refined-pristine-leather-package', displayName: 'Refined Pristine Leather Package', type: 'cargo', tier: Tier.T8 },
  { id: 'refined-pristine-wood-plank-package', displayName: 'Refined Pristine Wood Plank Package', type: 'cargo', tier: Tier.T8 },
  { id: 'tier-8-animal', displayName: 'Tier 8 Animal', type: 'cargo', tier: Tier.T8 },
  { id: 'magnificient-brick-package', displayName: 'Magnificient Brick Package', type: 'cargo', tier: Tier.T9 },
  { id: 'magnificient-brick-slab', displayName: 'Magnificient Brick Slab', type: 'cargo', tier: Tier.T9 },
  { id: 'magnificient-chemical-supply-pack', displayName: 'Magnificient Chemical Supply Pack', type: 'cargo', tier: Tier.T9 },
  { id: 'magnificient-cloth-package', displayName: 'Magnificient Cloth Package', type: 'cargo', tier: Tier.T9 },
  { id: 'magnificient-cloth-tarp', displayName: 'Magnificient Cloth Tarp', type: 'cargo', tier: Tier.T9 },
  { id: 'magnificient-geode', displayName: 'Magnificient Geode', type: 'cargo', tier: Tier.T9 },
  { id: 'magnificient-leather-package', displayName: 'Magnificient Leather Package', type: 'cargo', tier: Tier.T9 },
  { id: 'magnificient-leather-sheeting', displayName: 'Magnificient Leather Sheeting', type: 'cargo', tier: Tier.T9 },
  { id: 'magnificient-ocean-fish', displayName: 'Magnificient Ocean Fish', type: 'cargo', tier: Tier.T9 },
  { id: 'magnificient-plant-roots', displayName: 'Magnificient Plant Roots', type: 'cargo', tier: Tier.T9 },
  { id: 'magnificient-rock-package', displayName: 'Magnificient Rock Package', type: 'cargo', tier: Tier.T9 },
  { id: 'magnificient-stone-carving-package', displayName: 'Magnificient Stone Carving Package', type: 'cargo', tier: Tier.T9 },
  { id: 'magnificient-stone-chunk', displayName: 'Magnificient Stone Chunk', type: 'cargo', tier: Tier.T9 },
  { id: 'magnificient-timber', displayName: 'Magnificient Timber', type: 'cargo', tier: Tier.T9 },
  { id: 'magnificient-trunk', displayName: 'Magnificient Trunk', type: 'cargo', tier: Tier.T9 },
  { id: 'magnificient-wood-log-package', displayName: 'Magnificient Wood Log Package', type: 'cargo', tier: Tier.T9 },
  { id: 'magnificient-wood-plank-package', displayName: 'Magnificient Wood Plank Package', type: 'cargo', tier: Tier.T9 },
  { id: 'refined-magnificient-brick-package', displayName: 'Refined Magnificient Brick Package', type: 'cargo', tier: Tier.T9 },
  { id: 'refined-magnificient-cloth-package', displayName: 'Refined Magnificient Cloth Package', type: 'cargo', tier: Tier.T9 },
  { id: 'refined-magnificient-leather-package', displayName: 'Refined Magnificient Leather Package', type: 'cargo', tier: Tier.T9 },
  { id: 'refined-magnificient-wood-plank-package', displayName: 'Refined Magnificient Wood Plank Package', type: 'cargo', tier: Tier.T9 },
  { id: 'refined-umbracite-ingot-package', displayName: 'Refined Umbracite Ingot Package', type: 'cargo', tier: Tier.T9 },
  { id: 'tier-9-animal', displayName: 'Tier 9 Animal', type: 'cargo', tier: Tier.T9 },
  { id: 'tundra-ox', displayName: 'Tundra Ox', type: 'cargo', tier: Tier.T9 },
  { id: 'umbracite-frames', displayName: 'Umbracite Frames', type: 'cargo', tier: Tier.T9 },
  { id: 'umbracite-ingot-package', displayName: 'Umbracite Ingot Package', type: 'cargo', tier: Tier.T9 },
  { id: 'umbracite-ore-chunk', displayName: 'Umbracite Ore Chunk', type: 'cargo', tier: Tier.T9 },
  { id: 'astralite-frames', displayName: 'Astralite Frames', type: 'cargo', tier: Tier.T10 },
  { id: 'astralite-ingot-package', displayName: 'Astralite Ingot Package', type: 'cargo', tier: Tier.T10 },
  { id: 'astralite-ore-chunk', displayName: 'Astralite Ore Chunk', type: 'cargo', tier: Tier.T10 },
  { id: 'desert-terrorbird', displayName: 'Desert Terrorbird', type: 'cargo', tier: Tier.T10 },
  { id: 'flawless-brick-package', displayName: 'Flawless Brick Package', type: 'cargo', tier: Tier.T10 },
  { id: 'flawless-brick-slab', displayName: 'Flawless Brick Slab', type: 'cargo', tier: Tier.T10 },
  { id: 'flawless-chemical-supply-pack', displayName: 'Flawless Chemical Supply Pack', type: 'cargo', tier: Tier.T10 },
  { id: 'flawless-cloth-package', displayName: 'Flawless Cloth Package', type: 'cargo', tier: Tier.T10 },
  { id: 'flawless-cloth-tarp', displayName: 'Flawless Cloth Tarp', type: 'cargo', tier: Tier.T10 },
  { id: 'flawless-geode', displayName: 'Flawless Geode', type: 'cargo', tier: Tier.T10 },
  { id: 'flawless-leather-package', displayName: 'Flawless Leather Package', type: 'cargo', tier: Tier.T10 },
  { id: 'flawless-leather-sheeting', displayName: 'Flawless Leather Sheeting', type: 'cargo', tier: Tier.T10 },
  { id: 'flawless-ocean-fish', displayName: 'Flawless Ocean Fish', type: 'cargo', tier: Tier.T10 },
  { id: 'flawless-plant-roots', displayName: 'Flawless Plant Roots', type: 'cargo', tier: Tier.T10 },
  { id: 'flawless-rock-package', displayName: 'Flawless Rock Package', type: 'cargo', tier: Tier.T10 },
  { id: 'flawless-stone-carving-package', displayName: 'Flawless Stone Carving Package', type: 'cargo', tier: Tier.T10 },
  { id: 'flawless-stone-chunk', displayName: 'Flawless Stone Chunk', type: 'cargo', tier: Tier.T10 },
  { id: 'flawless-timber', displayName: 'Flawless Timber', type: 'cargo', tier: Tier.T10 },
  { id: 'flawless-trunk', displayName: 'Flawless Trunk', type: 'cargo', tier: Tier.T10 },
  { id: 'flawless-wood-log-package', displayName: 'Flawless Wood Log Package', type: 'cargo', tier: Tier.T10 },
  { id: 'flawless-wood-plank-package', displayName: 'Flawless Wood Plank Package', type: 'cargo', tier: Tier.T10 },
  { id: 'refined-astralite-ingot-package', displayName: 'Refined Astralite Ingot Package', type: 'cargo', tier: Tier.T10 },
  { id: 'refined-flawless-brick-package', displayName: 'Refined Flawless Brick Package', type: 'cargo', tier: Tier.T10 },
  { id: 'refined-flawless-cloth-package', displayName: 'Refined Flawless Cloth Package', type: 'cargo', tier: Tier.T10 },
  { id: 'refined-flawless-leather-package', displayName: 'Refined Flawless Leather Package', type: 'cargo', tier: Tier.T10 },
  { id: 'refined-flawless-wood-plank-package', displayName: 'Refined Flawless Wood Plank Package', type: 'cargo', tier: Tier.T10 },
  { id: 'tier-10-animal', displayName: 'Tier 10 Animal', type: 'cargo', tier: Tier.T10 },
];
