import { ItemNode, Tier } from '../item-node';

export const items: ItemNode[] = [
  { id: 'basic-wispweave-products', displayName: 'Basic Wispweave Products', type: 'craftable', tier: Tier.T1 },
  { id: 'breezy-fin-darter-products', displayName: 'Breezy Fin Darter Products', type: 'craftable', tier: Tier.T1 },
  { id: 'ferralith-axe', displayName: 'Ferralith Axe', type: 'craftable', tier: Tier.T1 },
  { id: 'ferralith-bow', displayName: 'Ferralith Bow', type: 'craftable', tier: Tier.T1 },
  { id: 'ferralith-chisel', displayName: 'Ferralith Chisel', type: 'craftable', tier: Tier.T1 },
  { id: 'ferralith-crossbow', displayName: 'Ferralith Crossbow', type: 'craftable', tier: Tier.T1 },
  { id: 'ferralith-hammer', displayName: 'Ferralith Hammer', type: 'craftable', tier: Tier.T1 },
  { id: 'ferralith-hoe', displayName: 'Ferralith Hoe', type: 'craftable', tier: Tier.T1 },
  { id: 'ferralith-knife', displayName: 'Ferralith Knife', type: 'craftable', tier: Tier.T1 },
  { id: 'ferralith-machete', displayName: 'Ferralith Machete', type: 'craftable', tier: Tier.T1 },
  { id: 'ferralith-pickaxe', displayName: 'Ferralith Pickaxe', type: 'craftable', tier: Tier.T1 },
  { id: 'ferralith-quill', displayName: 'Ferralith Quill', type: 'craftable', tier: Tier.T1 },
  { id: 'ferralith-rod', displayName: 'Ferralith Rod', type: 'craftable', tier: Tier.T1 },
  { id: 'ferralith-saw', displayName: 'Ferralith Saw', type: 'craftable', tier: Tier.T1 },
  { id: 'flint-axe', displayName: 'Flint Axe', type: 'craftable', tier: Tier.T1 },
  { id: 'flint-bow', displayName: 'Flint Bow', type: 'craftable', tier: Tier.T1 },
  { id: 'flint-chisel', displayName: 'Flint Chisel', type: 'craftable', tier: Tier.T1 },
  { id: 'flint-hammer', displayName: 'Flint Hammer', type: 'craftable', tier: Tier.T1 },
  { id: 'flint-hoe', displayName: 'Flint Hoe', type: 'craftable', tier: Tier.T1 },
  { id: 'flint-knife', displayName: 'Flint Knife', type: 'craftable', tier: Tier.T1 },
  { id: 'flint-machete', displayName: 'Flint Machete', type: 'craftable', tier: Tier.T1 },
  { id: 'flint-pickaxe', displayName: 'Flint Pickaxe', type: 'craftable', tier: Tier.T1 },
  { id: 'flint-quill', displayName: 'Flint Quill', type: 'craftable', tier: Tier.T1 },
  { id: 'flint-rod', displayName: 'Flint Rod', type: 'craftable', tier: Tier.T1 },
  { id: 'flint-saw', displayName: 'Flint Saw', type: 'craftable', tier: Tier.T1 },
  { id: 'flint-tool-bundle', displayName: 'Flint Tool Bundle', type: 'craftable', tier: Tier.T1 },
  { id: 'flint-tool-bundle-ii', displayName: 'Flint Tool Bundle II', type: 'craftable', tier: Tier.T1 },
  { id: 'flint-tool-bundle-ii-output', displayName: 'Flint Tool Bundle II Output', type: 'craftable', tier: Tier.T1 },
  { id: 'flint-tool-bundle-output', displayName: 'Flint Tool Bundle Output', type: 'craftable', tier: Tier.T1 },
  { id: 'high-quality-rough-plank', displayName: 'High Quality Rough Plank', type: 'craftable', tier: Tier.T1 },
  { id: 'master-tool', displayName: 'Master Tool', type: 'craftable', tier: Tier.T1 },
  { id: 'oceancrest-marlin-products', displayName: 'Oceancrest Marlin Products', type: 'craftable', tier: Tier.T1 },
  { id: 'refined-rough-plank', displayName: 'Refined Rough Plank', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-plank', displayName: 'Rough Plank', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-plank-output', displayName: 'Rough Plank Output', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-tool-handle', displayName: 'Rough Tool Handle', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-untreated-plank', displayName: 'Rough Untreated Plank', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-untreated-plank-output', displayName: 'Rough Untreated Plank Output', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-woven-shoes', displayName: 'Rough Woven Shoes', type: 'craftable', tier: Tier.T1 },
  { id: 'simple-rough-shoes', displayName: 'Simple Rough Shoes', type: 'craftable', tier: Tier.T1 },
  { id: 'emberfin-shiner-products', displayName: 'Emberfin Shiner Products', type: 'craftable', tier: Tier.T2 },
  { id: 'high-quality-simple-plank', displayName: 'High Quality Simple Plank', type: 'craftable', tier: Tier.T2 },
  { id: 'pyrelite-axe', displayName: 'Pyrelite Axe', type: 'craftable', tier: Tier.T2 },
  { id: 'pyrelite-bow', displayName: 'Pyrelite Bow', type: 'craftable', tier: Tier.T2 },
  { id: 'pyrelite-chisel', displayName: 'Pyrelite Chisel', type: 'craftable', tier: Tier.T2 },
  { id: 'pyrelite-crossbow', displayName: 'Pyrelite Crossbow', type: 'craftable', tier: Tier.T2 },
  { id: 'pyrelite-hammer', displayName: 'Pyrelite Hammer', type: 'craftable', tier: Tier.T2 },
  { id: 'pyrelite-hoe', displayName: 'Pyrelite Hoe', type: 'craftable', tier: Tier.T2 },
  { id: 'pyrelite-knife', displayName: 'Pyrelite Knife', type: 'craftable', tier: Tier.T2 },
  { id: 'pyrelite-machete', displayName: 'Pyrelite Machete', type: 'craftable', tier: Tier.T2 },
  { id: 'pyrelite-pickaxe', displayName: 'Pyrelite Pickaxe', type: 'craftable', tier: Tier.T2 },
  { id: 'pyrelite-quill', displayName: 'Pyrelite Quill', type: 'craftable', tier: Tier.T2 },
  { id: 'pyrelite-rod', displayName: 'Pyrelite Rod', type: 'craftable', tier: Tier.T2 },
  { id: 'pyrelite-saw', displayName: 'Pyrelite Saw', type: 'craftable', tier: Tier.T2 },
  { id: 'refined-simple-plank', displayName: 'Refined Simple Plank', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-plank', displayName: 'Simple Plank', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-plank-output', displayName: 'Simple Plank Output', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-tool-handle', displayName: 'Simple Tool Handle', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-untreated-plank', displayName: 'Simple Untreated Plank', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-untreated-plank-output', displayName: 'Simple Untreated Plank Output', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-wispweave-products', displayName: 'Simple Wispweave Products', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-woven-shoes', displayName: 'Simple Woven Shoes', type: 'craftable', tier: Tier.T2 },
  { id: 'coralcrest-darter-products', displayName: 'Coralcrest Darter Products', type: 'craftable', tier: Tier.T3 },
  { id: 'emarium-axe', displayName: 'Emarium Axe', type: 'craftable', tier: Tier.T3 },
  { id: 'emarium-bow', displayName: 'Emarium Bow', type: 'craftable', tier: Tier.T3 },
  { id: 'emarium-chisel', displayName: 'Emarium Chisel', type: 'craftable', tier: Tier.T3 },
  { id: 'emarium-crossbow', displayName: 'Emarium Crossbow', type: 'craftable', tier: Tier.T3 },
  { id: 'emarium-hammer', displayName: 'Emarium Hammer', type: 'craftable', tier: Tier.T3 },
  { id: 'emarium-hoe', displayName: 'Emarium Hoe', type: 'craftable', tier: Tier.T3 },
  { id: 'emarium-knife', displayName: 'Emarium Knife', type: 'craftable', tier: Tier.T3 },
  { id: 'emarium-machete', displayName: 'Emarium Machete', type: 'craftable', tier: Tier.T3 },
  { id: 'emarium-pickaxe', displayName: 'Emarium Pickaxe', type: 'craftable', tier: Tier.T3 },
  { id: 'emarium-quill', displayName: 'Emarium Quill', type: 'craftable', tier: Tier.T3 },
  { id: 'emarium-rod', displayName: 'Emarium Rod', type: 'craftable', tier: Tier.T3 },
  { id: 'emarium-saw', displayName: 'Emarium Saw', type: 'craftable', tier: Tier.T3 },
  { id: 'high-quality-sturdy-plank', displayName: 'High Quality Sturdy Plank', type: 'craftable', tier: Tier.T3 },
  { id: 'infused-wispweave-products', displayName: 'Infused Wispweave Products', type: 'craftable', tier: Tier.T3 },
  { id: 'refined-sturdy-plank', displayName: 'Refined Sturdy Plank', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-plank', displayName: 'Sturdy Plank', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-plank-output', displayName: 'Sturdy Plank Output', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-tool-handle', displayName: 'Sturdy Tool Handle', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-untreated-plank', displayName: 'Sturdy Untreated Plank', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-untreated-plank-output', displayName: 'Sturdy Untreated Plank Output', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-woven-shoes', displayName: 'Sturdy Woven Shoes', type: 'craftable', tier: Tier.T3 },
  { id: 'wavecrest-eel-products', displayName: 'Wavecrest Eel Products', type: 'craftable', tier: Tier.T3 },
  { id: 'elenvar-axe', displayName: 'Elenvar Axe', type: 'craftable', tier: Tier.T4 },
  { id: 'elenvar-bow', displayName: 'Elenvar Bow', type: 'craftable', tier: Tier.T4 },
  { id: 'elenvar-chisel', displayName: 'Elenvar Chisel', type: 'craftable', tier: Tier.T4 },
  { id: 'elenvar-crossbow', displayName: 'Elenvar Crossbow', type: 'craftable', tier: Tier.T4 },
  { id: 'elenvar-hammer', displayName: 'Elenvar Hammer', type: 'craftable', tier: Tier.T4 },
  { id: 'elenvar-hoe', displayName: 'Elenvar Hoe', type: 'craftable', tier: Tier.T4 },
  { id: 'elenvar-knife', displayName: 'Elenvar Knife', type: 'craftable', tier: Tier.T4 },
  { id: 'elenvar-machete', displayName: 'Elenvar Machete', type: 'craftable', tier: Tier.T4 },
  { id: 'elenvar-pickaxe', displayName: 'Elenvar Pickaxe', type: 'craftable', tier: Tier.T4 },
  { id: 'elenvar-quill', displayName: 'Elenvar Quill', type: 'craftable', tier: Tier.T4 },
  { id: 'elenvar-rod', displayName: 'Elenvar Rod', type: 'craftable', tier: Tier.T4 },
  { id: 'elenvar-saw', displayName: 'Elenvar Saw', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-plank', displayName: 'Fine Plank', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-plank-output', displayName: 'Fine Plank Output', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-tool-handle', displayName: 'Fine Tool Handle', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-untreated-plank', displayName: 'Fine Untreated Plank', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-untreated-plank-output', displayName: 'Fine Untreated Plank Output', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-wispweave-products', displayName: 'Fine Wispweave Products', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-woven-shoes', displayName: 'Fine Woven Shoes', type: 'craftable', tier: Tier.T4 },
  { id: 'high-quality-fine-plank', displayName: 'High Quality Fine Plank', type: 'craftable', tier: Tier.T4 },
  { id: 'mossfin-chub-products', displayName: 'Mossfin Chub Products', type: 'craftable', tier: Tier.T4 },
  { id: 'refined-fine-plank', displayName: 'Refined Fine Plank', type: 'craftable', tier: Tier.T4 },
  { id: 'seastorm-tuna-products', displayName: 'Seastorm Tuna Products', type: 'craftable', tier: Tier.T4 },
  { id: 'azure-shark-products', displayName: 'Azure Shark Products', type: 'craftable', tier: Tier.T5 },
  { id: 'emberscale-sturgeon-products', displayName: 'Emberscale Sturgeon Products', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-plank', displayName: 'Exquisite Plank', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-plank-output', displayName: 'Exquisite Plank Output', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-tool-handle', displayName: 'Exquisite Tool Handle', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-untreated-plank', displayName: 'Exquisite Untreated Plank', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-untreated-plank-output', displayName: 'Exquisite Untreated Plank Output', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-wispweave-products', displayName: 'Exquisite Wispweave Products', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-woven-shoes', displayName: 'Exquisite Woven Shoes', type: 'craftable', tier: Tier.T5 },
  { id: 'high-quality-exquisite-plank', displayName: 'High Quality Exquisite Plank', type: 'craftable', tier: Tier.T5 },
  { id: 'luminite-axe', displayName: 'Luminite Axe', type: 'craftable', tier: Tier.T5 },
  { id: 'luminite-bow', displayName: 'Luminite Bow', type: 'craftable', tier: Tier.T5 },
  { id: 'luminite-chisel', displayName: 'Luminite Chisel', type: 'craftable', tier: Tier.T5 },
  { id: 'luminite-crossbow', displayName: 'Luminite Crossbow', type: 'craftable', tier: Tier.T5 },
  { id: 'luminite-hammer', displayName: 'Luminite Hammer', type: 'craftable', tier: Tier.T5 },
  { id: 'luminite-hoe', displayName: 'Luminite Hoe', type: 'craftable', tier: Tier.T5 },
  { id: 'luminite-knife', displayName: 'Luminite Knife', type: 'craftable', tier: Tier.T5 },
  { id: 'luminite-machete', displayName: 'Luminite Machete', type: 'craftable', tier: Tier.T5 },
  { id: 'luminite-pickaxe', displayName: 'Luminite Pickaxe', type: 'craftable', tier: Tier.T5 },
  { id: 'luminite-quill', displayName: 'Luminite Quill', type: 'craftable', tier: Tier.T5 },
  { id: 'luminite-rod', displayName: 'Luminite Rod', type: 'craftable', tier: Tier.T5 },
  { id: 'luminite-saw', displayName: 'Luminite Saw', type: 'craftable', tier: Tier.T5 },
  { id: 'refined-exquisite-plank', displayName: 'Refined Exquisite Plank', type: 'craftable', tier: Tier.T5 },
  { id: 'hexfin-perch-products', displayName: 'Hexfin Perch Products', type: 'craftable', tier: Tier.T6 },
  { id: 'high-quality-peerless-plank', displayName: 'High Quality Peerless Plank', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-plank', displayName: 'Peerless Plank', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-plank-output', displayName: 'Peerless Plank Output', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-tool-handle', displayName: 'Peerless Tool Handle', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-untreated-plank', displayName: 'Peerless Untreated Plank', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-untreated-plank-output', displayName: 'Peerless Untreated Plank Output', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-wispweave-products', displayName: 'Peerless Wispweave Products', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-woven-shoes', displayName: 'Peerless Woven Shoes', type: 'craftable', tier: Tier.T6 },
  { id: 'rathium-axe', displayName: 'Rathium Axe', type: 'craftable', tier: Tier.T6 },
  { id: 'rathium-bow', displayName: 'Rathium Bow', type: 'craftable', tier: Tier.T6 },
  { id: 'rathium-chisel', displayName: 'Rathium Chisel', type: 'craftable', tier: Tier.T6 },
  { id: 'rathium-crossbow', displayName: 'Rathium Crossbow', type: 'craftable', tier: Tier.T6 },
  { id: 'rathium-hammer', displayName: 'Rathium Hammer', type: 'craftable', tier: Tier.T6 },
  { id: 'rathium-hoe', displayName: 'Rathium Hoe', type: 'craftable', tier: Tier.T6 },
  { id: 'rathium-knife', displayName: 'Rathium Knife', type: 'craftable', tier: Tier.T6 },
  { id: 'rathium-machete', displayName: 'Rathium Machete', type: 'craftable', tier: Tier.T6 },
  { id: 'rathium-pickaxe', displayName: 'Rathium Pickaxe', type: 'craftable', tier: Tier.T6 },
  { id: 'rathium-quill', displayName: 'Rathium Quill', type: 'craftable', tier: Tier.T6 },
  { id: 'rathium-rod', displayName: 'Rathium Rod', type: 'craftable', tier: Tier.T6 },
  { id: 'rathium-saw', displayName: 'Rathium Saw', type: 'craftable', tier: Tier.T6 },
  { id: 'refined-peerless-plank', displayName: 'Refined Peerless Plank', type: 'craftable', tier: Tier.T6 },
  { id: 'aurumite-axe', displayName: 'Aurumite Axe', type: 'craftable', tier: Tier.T7 },
  { id: 'aurumite-bow', displayName: 'Aurumite Bow', type: 'craftable', tier: Tier.T7 },
  { id: 'aurumite-chisel', displayName: 'Aurumite Chisel', type: 'craftable', tier: Tier.T7 },
  { id: 'aurumite-crossbow', displayName: 'Aurumite Crossbow', type: 'craftable', tier: Tier.T7 },
  { id: 'aurumite-hammer', displayName: 'Aurumite Hammer', type: 'craftable', tier: Tier.T7 },
  { id: 'aurumite-hoe', displayName: 'Aurumite Hoe', type: 'craftable', tier: Tier.T7 },
  { id: 'aurumite-knife', displayName: 'Aurumite Knife', type: 'craftable', tier: Tier.T7 },
  { id: 'aurumite-machete', displayName: 'Aurumite Machete', type: 'craftable', tier: Tier.T7 },
  { id: 'aurumite-pickaxe', displayName: 'Aurumite Pickaxe', type: 'craftable', tier: Tier.T7 },
  { id: 'aurumite-quill', displayName: 'Aurumite Quill', type: 'craftable', tier: Tier.T7 },
  { id: 'aurumite-rod', displayName: 'Aurumite Rod', type: 'craftable', tier: Tier.T7 },
  { id: 'aurumite-saw', displayName: 'Aurumite Saw', type: 'craftable', tier: Tier.T7 },
  { id: 'ornate-plank', displayName: 'Ornate Plank', type: 'craftable', tier: Tier.T7 },
  { id: 'ornate-wispweave-products', displayName: 'Ornate Wispweave Products', type: 'craftable', tier: Tier.T7 },
  { id: 'ornate-woven-shoes', displayName: 'Ornate Woven Shoes', type: 'craftable', tier: Tier.T7 },
  { id: 'refined-ornate-plank', displayName: 'Refined Ornate Plank', type: 'craftable', tier: Tier.T7 },
  { id: 'speedy-glowfin-products', displayName: 'Speedy Glowfin Products', type: 'craftable', tier: Tier.T7 },
  { id: 'tidebreaker-barracuda-products', displayName: 'Tidebreaker Barracuda Products', type: 'craftable', tier: Tier.T7 },
  { id: 'celestium-axe', displayName: 'Celestium Axe', type: 'craftable', tier: Tier.T8 },
  { id: 'celestium-bow', displayName: 'Celestium Bow', type: 'craftable', tier: Tier.T8 },
  { id: 'celestium-chisel', displayName: 'Celestium Chisel', type: 'craftable', tier: Tier.T8 },
  { id: 'celestium-crossbow', displayName: 'Celestium Crossbow', type: 'craftable', tier: Tier.T8 },
  { id: 'celestium-hammer', displayName: 'Celestium Hammer', type: 'craftable', tier: Tier.T8 },
  { id: 'celestium-hoe', displayName: 'Celestium Hoe', type: 'craftable', tier: Tier.T8 },
  { id: 'celestium-knife', displayName: 'Celestium Knife', type: 'craftable', tier: Tier.T8 },
  { id: 'celestium-machete', displayName: 'Celestium Machete', type: 'craftable', tier: Tier.T8 },
  { id: 'celestium-pickaxe', displayName: 'Celestium Pickaxe', type: 'craftable', tier: Tier.T8 },
  { id: 'celestium-quill', displayName: 'Celestium Quill', type: 'craftable', tier: Tier.T8 },
  { id: 'celestium-rod', displayName: 'Celestium Rod', type: 'craftable', tier: Tier.T8 },
  { id: 'celestium-saw', displayName: 'Celestium Saw', type: 'craftable', tier: Tier.T8 },
  { id: 'pristine-plank', displayName: 'Pristine Plank', type: 'craftable', tier: Tier.T8 },
  { id: 'pristine-wispweave-products', displayName: 'Pristine Wispweave Products', type: 'craftable', tier: Tier.T8 },
  { id: 'pristine-woven-shoes', displayName: 'Pristine Woven Shoes', type: 'craftable', tier: Tier.T8 },
  { id: 'rainbowscaled-tilapia', displayName: 'Rainbowscaled Tilapia', type: 'craftable', tier: Tier.T8 },
  { id: 'rainbowscaled-tilapia-filet', displayName: 'Rainbowscaled Tilapia Filet', type: 'craftable', tier: Tier.T8 },
  { id: 'rainbowscaled-tilapia-products', displayName: 'Rainbowscaled Tilapia Products', type: 'craftable', tier: Tier.T8 },
  { id: 'refined-pristine-plank', displayName: 'Refined Pristine Plank', type: 'craftable', tier: Tier.T8 },
  { id: 'magnificient-plank', displayName: 'Magnificient Plank', type: 'craftable', tier: Tier.T9 },
  { id: 'magnificient-wispweave-products', displayName: 'Magnificient Wispweave Products', type: 'craftable', tier: Tier.T9 },
  { id: 'magnificient-woven-shoes', displayName: 'Magnificient Woven Shoes', type: 'craftable', tier: Tier.T9 },
  { id: 'refined-magnificient-plank', displayName: 'Refined Magnificient Plank', type: 'craftable', tier: Tier.T9 },
  { id: 'umbracite-axe', displayName: 'Umbracite Axe', type: 'craftable', tier: Tier.T9 },
  { id: 'umbracite-bow', displayName: 'Umbracite Bow', type: 'craftable', tier: Tier.T9 },
  { id: 'umbracite-chisel', displayName: 'Umbracite Chisel', type: 'craftable', tier: Tier.T9 },
  { id: 'umbracite-crossbow', displayName: 'Umbracite Crossbow', type: 'craftable', tier: Tier.T9 },
  { id: 'umbracite-hammer', displayName: 'Umbracite Hammer', type: 'craftable', tier: Tier.T9 },
  { id: 'umbracite-hoe', displayName: 'Umbracite Hoe', type: 'craftable', tier: Tier.T9 },
  { id: 'umbracite-knife', displayName: 'Umbracite Knife', type: 'craftable', tier: Tier.T9 },
  { id: 'umbracite-machete', displayName: 'Umbracite Machete', type: 'craftable', tier: Tier.T9 },
  { id: 'umbracite-pickaxe', displayName: 'Umbracite Pickaxe', type: 'craftable', tier: Tier.T9 },
  { id: 'umbracite-quill', displayName: 'Umbracite Quill', type: 'craftable', tier: Tier.T9 },
  { id: 'umbracite-rod', displayName: 'Umbracite Rod', type: 'craftable', tier: Tier.T9 },
  { id: 'umbracite-saw', displayName: 'Umbracite Saw', type: 'craftable', tier: Tier.T9 },
  { id: 'astralite-axe', displayName: 'Astralite Axe', type: 'craftable', tier: Tier.T10 },
  { id: 'astralite-bow', displayName: 'Astralite Bow', type: 'craftable', tier: Tier.T10 },
  { id: 'astralite-chisel', displayName: 'Astralite Chisel', type: 'craftable', tier: Tier.T10 },
  { id: 'astralite-crossbow', displayName: 'Astralite Crossbow', type: 'craftable', tier: Tier.T10 },
  { id: 'astralite-hammer', displayName: 'Astralite Hammer', type: 'craftable', tier: Tier.T10 },
  { id: 'astralite-hoe', displayName: 'Astralite Hoe', type: 'craftable', tier: Tier.T10 },
  { id: 'astralite-knife', displayName: 'Astralite Knife', type: 'craftable', tier: Tier.T10 },
  { id: 'astralite-machete', displayName: 'Astralite Machete', type: 'craftable', tier: Tier.T10 },
  { id: 'astralite-pickaxe', displayName: 'Astralite Pickaxe', type: 'craftable', tier: Tier.T10 },
  { id: 'astralite-quill', displayName: 'Astralite Quill', type: 'craftable', tier: Tier.T10 },
  { id: 'astralite-rod', displayName: 'Astralite Rod', type: 'craftable', tier: Tier.T10 },
  { id: 'astralite-saw', displayName: 'Astralite Saw', type: 'craftable', tier: Tier.T10 },
  { id: 'flawless-plank', displayName: 'Flawless Plank', type: 'craftable', tier: Tier.T10 },
  { id: 'flawless-wispweave-products', displayName: 'Flawless Wispweave Products', type: 'craftable', tier: Tier.T10 },
  { id: 'flawless-woven-shoes', displayName: 'Flawless Woven Shoes', type: 'craftable', tier: Tier.T10 },
  { id: 'refined-flawless-plank', displayName: 'Refined Flawless Plank', type: 'craftable', tier: Tier.T10 },
];
