import { ItemNode, Tier } from '../item-node';

export const items: ItemNode[] = [
  { id: 'basic-cloth-footwraps', displayName: 'Basic Cloth Footwraps', type: 'craftable', tier: Tier.T1 },
  { id: 'beginners-cloth-research', displayName: 'Beginner\'s Cloth Research', type: 'craftable', tier: Tier.T1 },
  { id: 'cloth-armwraps', displayName: 'Cloth Armwraps', type: 'craftable', tier: Tier.T1 },
  { id: 'high-quality-rough-cloth', displayName: 'High Quality Rough Cloth', type: 'craftable', tier: Tier.T1 },
  { id: 'long-cloth-gloves', displayName: 'Long Cloth Gloves', type: 'craftable', tier: Tier.T1 },
  { id: 'refined-rough-cloth', displayName: 'Refined Rough Cloth', type: 'craftable', tier: Tier.T1 },
  { id: 'rope-belt', displayName: 'Rope Belt', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-cloth', displayName: 'Rough Cloth', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-cloth-output', displayName: 'Rough Cloth Output', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-cloth-strip', displayName: 'Rough Cloth Strip', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-fabric', displayName: 'Rough Fabric', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-rope', displayName: 'Rough Rope', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-spool-of-thread', displayName: 'Rough Spool Of Thread', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-twine', displayName: 'Rough Twine', type: 'craftable', tier: Tier.T1 },
  { id: 'simple-cloth-footwraps', displayName: 'Simple Cloth Footwraps', type: 'craftable', tier: Tier.T1 },
  { id: 'simple-cloth-gloves', displayName: 'Simple Cloth Gloves', type: 'craftable', tier: Tier.T1 },
  { id: 'high-quality-simple-cloth', displayName: 'High Quality Simple Cloth', type: 'craftable', tier: Tier.T2 },
  { id: 'novices-cloth-research', displayName: 'Novice\'s Cloth Research', type: 'craftable', tier: Tier.T2 },
  { id: 'refined-simple-cloth', displayName: 'Refined Simple Cloth', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-cloth', displayName: 'Simple Cloth', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-cloth-output', displayName: 'Simple Cloth Output', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-cloth-strip', displayName: 'Simple Cloth Strip', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-fabric', displayName: 'Simple Fabric', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-rope', displayName: 'Simple Rope', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-spool-of-thread', displayName: 'Simple Spool Of Thread', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-twine', displayName: 'Simple Twine', type: 'craftable', tier: Tier.T2 },
  { id: 'essential-cloth-research', displayName: 'Essential Cloth Research', type: 'craftable', tier: Tier.T3 },
  { id: 'high-quality-sturdy-cloth', displayName: 'High Quality Sturdy Cloth', type: 'craftable', tier: Tier.T3 },
  { id: 'refined-sturdy-cloth', displayName: 'Refined Sturdy Cloth', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-cloth', displayName: 'Sturdy Cloth', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-cloth-output', displayName: 'Sturdy Cloth Output', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-cloth-strip', displayName: 'Sturdy Cloth Strip', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-fabric', displayName: 'Sturdy Fabric', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-rope', displayName: 'Sturdy Rope', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-spool-of-thread', displayName: 'Sturdy Spool Of Thread', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-twine', displayName: 'Sturdy Twine', type: 'craftable', tier: Tier.T3 },
  { id: 'fine-cloth', displayName: 'Fine Cloth', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-cloth-output', displayName: 'Fine Cloth Output', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-cloth-strip', displayName: 'Fine Cloth Strip', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-fabric', displayName: 'Fine Fabric', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-rope', displayName: 'Fine Rope', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-spool-of-thread', displayName: 'Fine Spool Of Thread', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-twine', displayName: 'Fine Twine', type: 'craftable', tier: Tier.T4 },
  { id: 'high-quality-fine-cloth', displayName: 'High Quality Fine Cloth', type: 'craftable', tier: Tier.T4 },
  { id: 'proficient-cloth-research', displayName: 'Proficient Cloth Research', type: 'craftable', tier: Tier.T4 },
  { id: 'refined-fine-cloth', displayName: 'Refined Fine Cloth', type: 'craftable', tier: Tier.T4 },
  { id: 'advanced-cloth-research', displayName: 'Advanced Cloth Research', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-cloth', displayName: 'Exquisite Cloth', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-cloth-output', displayName: 'Exquisite Cloth Output', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-cloth-strip', displayName: 'Exquisite Cloth Strip', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-fabric', displayName: 'Exquisite Fabric', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-rope', displayName: 'Exquisite Rope', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-spool-of-thread', displayName: 'Exquisite Spool Of Thread', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-twine', displayName: 'Exquisite Twine', type: 'craftable', tier: Tier.T5 },
  { id: 'high-quality-exquisite-cloth', displayName: 'High Quality Exquisite Cloth', type: 'craftable', tier: Tier.T5 },
  { id: 'refined-exquisite-cloth', displayName: 'Refined Exquisite Cloth', type: 'craftable', tier: Tier.T5 },
  { id: 'comprehensive-cloth-research', displayName: 'Comprehensive Cloth Research', type: 'craftable', tier: Tier.T6 },
  { id: 'high-quality-peerless-cloth', displayName: 'High Quality Peerless Cloth', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-cloth', displayName: 'Peerless Cloth', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-cloth-output', displayName: 'Peerless Cloth Output', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-cloth-strip', displayName: 'Peerless Cloth Strip', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-fabric', displayName: 'Peerless Fabric', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-rope', displayName: 'Peerless Rope', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-spool-of-thread', displayName: 'Peerless Spool Of Thread', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-twine', displayName: 'Peerless Twine', type: 'craftable', tier: Tier.T6 },
  { id: 'refined-peerless-cloth', displayName: 'Refined Peerless Cloth', type: 'craftable', tier: Tier.T6 },
  { id: 'ornate-cloth', displayName: 'Ornate Cloth', type: 'craftable', tier: Tier.T7 },
  { id: 'ornate-cloth-research', displayName: 'Ornate Cloth Research', type: 'craftable', tier: Tier.T7 },
  { id: 'ornate-cloth-strip', displayName: 'Ornate Cloth Strip', type: 'craftable', tier: Tier.T7 },
  { id: 'ornate-rope', displayName: 'Ornate Rope', type: 'craftable', tier: Tier.T7 },
  { id: 'ornate-spool-of-thread', displayName: 'Ornate Spool Of Thread', type: 'craftable', tier: Tier.T7 },
  { id: 'refined-ornate-cloth', displayName: 'Refined Ornate Cloth', type: 'craftable', tier: Tier.T7 },
  { id: 'pristine-cloth', displayName: 'Pristine Cloth', type: 'craftable', tier: Tier.T8 },
  { id: 'pristine-cloth-research', displayName: 'Pristine Cloth Research', type: 'craftable', tier: Tier.T8 },
  { id: 'pristine-cloth-strip', displayName: 'Pristine Cloth Strip', type: 'craftable', tier: Tier.T8 },
  { id: 'pristine-rope', displayName: 'Pristine Rope', type: 'craftable', tier: Tier.T8 },
  { id: 'pristine-spool-of-thread', displayName: 'Pristine Spool Of Thread', type: 'craftable', tier: Tier.T8 },
  { id: 'refined-pristine-cloth', displayName: 'Refined Pristine Cloth', type: 'craftable', tier: Tier.T8 },
  { id: 'magnificient-cloth', displayName: 'Magnificient Cloth', type: 'craftable', tier: Tier.T9 },
  { id: 'magnificient-cloth-research', displayName: 'Magnificient Cloth Research', type: 'craftable', tier: Tier.T9 },
  { id: 'magnificient-cloth-strip', displayName: 'Magnificient Cloth Strip', type: 'craftable', tier: Tier.T9 },
  { id: 'magnificient-rope', displayName: 'Magnificient Rope', type: 'craftable', tier: Tier.T9 },
  { id: 'magnificient-spool-of-thread', displayName: 'Magnificient Spool Of Thread', type: 'craftable', tier: Tier.T9 },
  { id: 'refined-magnificient-cloth', displayName: 'Refined Magnificient Cloth', type: 'craftable', tier: Tier.T9 },
  { id: 'flawless-cloth', displayName: 'Flawless Cloth', type: 'craftable', tier: Tier.T10 },
  { id: 'flawless-cloth-research', displayName: 'Flawless Cloth Research', type: 'craftable', tier: Tier.T10 },
  { id: 'flawless-cloth-strip', displayName: 'Flawless Cloth Strip', type: 'craftable', tier: Tier.T10 },
  { id: 'flawless-rope', displayName: 'Flawless Rope', type: 'craftable', tier: Tier.T10 },
  { id: 'flawless-spool-of-thread', displayName: 'Flawless Spool Of Thread', type: 'craftable', tier: Tier.T10 },
  { id: 'refined-flawless-cloth', displayName: 'Refined Flawless Cloth', type: 'craftable', tier: Tier.T10 },
];
