import { ItemNode, Tier } from '../item-node';

export const items: ItemNode[] = [
  { id: 'basic-leather-treatment', displayName: 'Basic Leather Treatment', type: 'craftable', tier: Tier.T1 },
  { id: 'beginners-leather-research', displayName: "Beginner's Leather Research", type: 'craftable', tier: Tier.T1 },
  { id: 'refined-rough-leather', displayName: 'Refined Rough Leather', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-leather', displayName: 'Rough Leather', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-leather-belt', displayName: 'Rough Leather Belt', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-leather-boots', displayName: 'Rough Leather Boots', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-leather-cap', displayName: 'Rough Leather Cap', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-leather-gloves', displayName: 'Rough Leather Gloves', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-leather-leggings', displayName: 'Rough Leather Leggings', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-leather-shirt', displayName: 'Rough Leather Shirt', type: 'craftable', tier: Tier.T1 },
  { id: 'novices-leather-research', displayName: 'Novice\'s Leather Research', type: 'craftable', tier: Tier.T2 },
  { id: 'refined-simple-leather', displayName: 'Refined Simple Leather', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-leather', displayName: 'Simple Leather', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-leather-belt', displayName: 'Simple Leather Belt', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-leather-boots', displayName: 'Simple Leather Boots', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-leather-cap', displayName: 'Simple Leather Cap', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-leather-gloves', displayName: 'Simple Leather Gloves', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-leather-leggings', displayName: 'Simple Leather Leggings', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-leather-shirt', displayName: 'Simple Leather Shirt', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-leather-treatment', displayName: 'Simple Leather Treatment', type: 'craftable', tier: Tier.T2 },
  { id: 'essential-leather-research', displayName: 'Essential Leather Research', type: 'craftable', tier: Tier.T3 },
  { id: 'infused-leather-treatment', displayName: 'Infused Leather Treatment', type: 'craftable', tier: Tier.T3 },
  { id: 'refined-sturdy-leather', displayName: 'Refined Sturdy Leather', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-leather', displayName: 'Sturdy Leather', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-leather-belt', displayName: 'Sturdy Leather Belt', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-leather-boots', displayName: 'Sturdy Leather Boots', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-leather-cap', displayName: 'Sturdy Leather Cap', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-leather-gloves', displayName: 'Sturdy Leather Gloves', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-leather-leggings', displayName: 'Sturdy Leather Leggings', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-leather-shirt', displayName: 'Sturdy Leather Shirt', type: 'craftable', tier: Tier.T3 },
  { id: 'fine-leather', displayName: 'Fine Leather', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-leather-belt', displayName: 'Fine Leather Belt', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-leather-boots', displayName: 'Fine Leather Boots', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-leather-cap', displayName: 'Fine Leather Cap', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-leather-gloves', displayName: 'Fine Leather Gloves', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-leather-leggings', displayName: 'Fine Leather Leggings', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-leather-shirt', displayName: 'Fine Leather Shirt', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-leather-treatment', displayName: 'Fine Leather Treatment', type: 'craftable', tier: Tier.T4 },
  { id: 'proficient-leather-research', displayName: 'Proficient Leather Research', type: 'craftable', tier: Tier.T4 },
  { id: 'refined-fine-leather', displayName: 'Refined Fine Leather', type: 'craftable', tier: Tier.T4 },
  { id: 'advanced-leather-research', displayName: 'Advanced Leather Research', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-leather', displayName: 'Exquisite Leather', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-leather-belt', displayName: 'Exquisite Leather Belt', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-leather-boots', displayName: 'Exquisite Leather Boots', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-leather-cap', displayName: 'Exquisite Leather Cap', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-leather-gloves', displayName: 'Exquisite Leather Gloves', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-leather-leggings', displayName: 'Exquisite Leather Leggings', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-leather-shirt', displayName: 'Exquisite Leather Shirt', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-leather-treatment', displayName: 'Exquisite Leather Treatment', type: 'craftable', tier: Tier.T5 },
  { id: 'refined-exquisite-leather', displayName: 'Refined Exquisite Leather', type: 'craftable', tier: Tier.T5 },
  { id: 'comprehensive-leather-research', displayName: 'Comprehensive Leather Research', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-leather', displayName: 'Peerless Leather', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-leather-belt', displayName: 'Peerless Leather Belt', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-leather-boots', displayName: 'Peerless Leather Boots', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-leather-cap', displayName: 'Peerless Leather Cap', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-leather-gloves', displayName: 'Peerless Leather Gloves', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-leather-leggings', displayName: 'Peerless Leather Leggings', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-leather-shirt', displayName: 'Peerless Leather Shirt', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-leather-treatment', displayName: 'Peerless Leather Treatment', type: 'craftable', tier: Tier.T6 },
  { id: 'refined-peerless-leather', displayName: 'Refined Peerless Leather', type: 'craftable', tier: Tier.T6 },
  { id: 'ornate-leather', displayName: 'Ornate Leather', type: 'craftable', tier: Tier.T7 },
  { id: 'ornate-leather-belt', displayName: 'Ornate Leather Belt', type: 'craftable', tier: Tier.T7 },
  { id: 'ornate-leather-boots', displayName: 'Ornate Leather Boots', type: 'craftable', tier: Tier.T7 },
  { id: 'ornate-leather-cap', displayName: 'Ornate Leather Cap', type: 'craftable', tier: Tier.T7 },
  { id: 'ornate-leather-gloves', displayName: 'Ornate Leather Gloves', type: 'craftable', tier: Tier.T7 },
  { id: 'ornate-leather-leggings', displayName: 'Ornate Leather Leggings', type: 'craftable', tier: Tier.T7 },
  { id: 'ornate-leather-research', displayName: 'Ornate Leather Research', type: 'craftable', tier: Tier.T7 },
  { id: 'ornate-leather-shirt', displayName: 'Ornate Leather Shirt', type: 'craftable', tier: Tier.T7 },
  { id: 'ornate-leather-treatment', displayName: 'Ornate Leather Treatment', type: 'craftable', tier: Tier.T7 },
  { id: 'refined-ornate-leather', displayName: 'Refined Ornate Leather', type: 'craftable', tier: Tier.T7 },
  { id: 'pristine-leather', displayName: 'Pristine Leather', type: 'craftable', tier: Tier.T8 },
  { id: 'pristine-leather-belt', displayName: 'Pristine Leather Belt', type: 'craftable', tier: Tier.T8 },
  { id: 'pristine-leather-boots', displayName: 'Pristine Leather Boots', type: 'craftable', tier: Tier.T8 },
  { id: 'pristine-leather-cap', displayName: 'Pristine Leather Cap', type: 'craftable', tier: Tier.T8 },
  { id: 'pristine-leather-gloves', displayName: 'Pristine Leather Gloves', type: 'craftable', tier: Tier.T8 },
  { id: 'pristine-leather-leggings', displayName: 'Pristine Leather Leggings', type: 'craftable', tier: Tier.T8 },
  { id: 'pristine-leather-research', displayName: 'Pristine Leather Research', type: 'craftable', tier: Tier.T8 },
  { id: 'pristine-leather-shirt', displayName: 'Pristine Leather Shirt', type: 'craftable', tier: Tier.T8 },
  { id: 'pristine-leather-treatment', displayName: 'Pristine Leather Treatment', type: 'craftable', tier: Tier.T8 },
  { id: 'refined-pristine-leather', displayName: 'Refined Pristine Leather', type: 'craftable', tier: Tier.T8 },
  { id: 'magnificient-leather', displayName: 'Magnificient Leather', type: 'craftable', tier: Tier.T9 },
  { id: 'magnificient-leather-belt', displayName: 'Magnificient Leather Belt', type: 'craftable', tier: Tier.T9 },
  { id: 'magnificient-leather-boots', displayName: 'Magnificient Leather Boots', type: 'craftable', tier: Tier.T9 },
  { id: 'magnificient-leather-cap', displayName: 'Magnificient Leather Cap', type: 'craftable', tier: Tier.T9 },
  { id: 'magnificient-leather-gloves', displayName: 'Magnificient Leather Gloves', type: 'craftable', tier: Tier.T9 },
  { id: 'magnificient-leather-leggings', displayName: 'Magnificient Leather Leggings', type: 'craftable', tier: Tier.T9 },
  { id: 'magnificient-leather-research', displayName: 'Magnificient Leather Research', type: 'craftable', tier: Tier.T9 },
  { id: 'magnificient-leather-shirt', displayName: 'Magnificient Leather Shirt', type: 'craftable', tier: Tier.T9 },
  { id: 'magnificient-leather-treatment', displayName: 'Magnificient Leather Treatment', type: 'craftable', tier: Tier.T9 },
  { id: 'refined-magnificient-leather', displayName: 'Refined Magnificient Leather', type: 'craftable', tier: Tier.T9 },
  { id: 'flawless-leather', displayName: 'Flawless Leather', type: 'craftable', tier: Tier.T10 },
  { id: 'flawless-leather-belt', displayName: 'Flawless Leather Belt', type: 'craftable', tier: Tier.T10 },
  { id: 'flawless-leather-boots', displayName: 'Flawless Leather Boots', type: 'craftable', tier: Tier.T10 },
  { id: 'flawless-leather-cap', displayName: 'Flawless Leather Cap', type: 'craftable', tier: Tier.T10 },
  { id: 'flawless-leather-gloves', displayName: 'Flawless Leather Gloves', type: 'craftable', tier: Tier.T10 },
  { id: 'flawless-leather-leggings', displayName: 'Flawless Leather Leggings', type: 'craftable', tier: Tier.T10 },
  { id: 'flawless-leather-research', displayName: 'Flawless Leather Research', type: 'craftable', tier: Tier.T10 },
  { id: 'flawless-leather-shirt', displayName: 'Flawless Leather Shirt', type: 'craftable', tier: Tier.T10 },
  { id: 'flawless-leather-treatment', displayName: 'Flawless Leather Treatment', type: 'craftable', tier: Tier.T10 },
  { id: 'refined-flawless-leather', displayName: 'Refined Flawless Leather', type: 'craftable', tier: Tier.T10 },
];
