import { ItemNode, Tier } from '../item-node';

export const items: ItemNode[] = [
  { id: 'basic-mortar', displayName: 'Basic Mortar', type: 'craftable', tier: Tier.T1 },
  { id: 'refined-rough-brick', displayName: 'Refined Rough Brick', type: 'craftable', tier: Tier.T1 },
  { id: 'rough-brick', displayName: 'Rough Brick', type: 'craftable', tier: Tier.T1 },
  { id: 'unfired-rough-brick', displayName: 'Unfired Rough Brick', type: 'craftable', tier: Tier.T1 },
  { id: 'refined-simple-brick', displayName: 'Refined Simple Brick', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-brick', displayName: 'Simple Brick', type: 'craftable', tier: Tier.T2 },
  { id: 'simple-mortar', displayName: 'Simple Mortar', type: 'craftable', tier: Tier.T2 },
  { id: 'unfired-simple-brick', displayName: 'Unfired Simple Brick', type: 'craftable', tier: Tier.T2 },
  { id: 'infused-mortar', displayName: 'Infused Mortar', type: 'craftable', tier: Tier.T3 },
  { id: 'refined-sturdy-brick', displayName: 'Refined Sturdy Brick', type: 'craftable', tier: Tier.T3 },
  { id: 'sturdy-brick', displayName: 'Sturdy Brick', type: 'craftable', tier: Tier.T3 },
  { id: 'unfired-sturdy-brick', displayName: 'Unfired Sturdy Brick', type: 'craftable', tier: Tier.T3 },
  { id: 'fine-brick', displayName: 'Fine Brick', type: 'craftable', tier: Tier.T4 },
  { id: 'fine-mortar', displayName: 'Fine Mortar', type: 'craftable', tier: Tier.T4 },
  { id: 'refined-fine-brick', displayName: 'Refined Fine Brick', type: 'craftable', tier: Tier.T4 },
  { id: 'unfired-fine-brick', displayName: 'Unfired Fine Brick', type: 'craftable', tier: Tier.T4 },
  { id: 'exquisite-brick', displayName: 'Exquisite Brick', type: 'craftable', tier: Tier.T5 },
  { id: 'exquisite-mortar', displayName: 'Exquisite Mortar', type: 'craftable', tier: Tier.T5 },
  { id: 'refined-exquisite-brick', displayName: 'Refined Exquisite Brick', type: 'craftable', tier: Tier.T5 },
  { id: 'unfired-exquisite-brick', displayName: 'Unfired Exquisite Brick', type: 'craftable', tier: Tier.T5 },
  { id: 'peerless-brick', displayName: 'Peerless Brick', type: 'craftable', tier: Tier.T6 },
  { id: 'peerless-mortar', displayName: 'Peerless Mortar', type: 'craftable', tier: Tier.T6 },
  { id: 'refined-peerless-brick', displayName: 'Refined Peerless Brick', type: 'craftable', tier: Tier.T6 },
  { id: 'unfired-peerless-brick', displayName: 'Unfired Peerless Brick', type: 'craftable', tier: Tier.T6 },
  { id: 'ornate-brick', displayName: 'Ornate Brick', type: 'craftable', tier: Tier.T7 },
  { id: 'refined-ornate-brick', displayName: 'Refined Ornate Brick', type: 'craftable', tier: Tier.T7 },
  { id: 'unfired-ornate-brick', displayName: 'Unfired Ornate Brick', type: 'craftable', tier: Tier.T7 },
  { id: 'pristine-brick', displayName: 'Pristine Brick', type: 'craftable', tier: Tier.T8 },
  { id: 'refined-pristine-brick', displayName: 'Refined Pristine Brick', type: 'craftable', tier: Tier.T8 },
  { id: 'unfired-pristine-brick', displayName: 'Unfired Pristine Brick', type: 'craftable', tier: Tier.T8 },
  { id: 'magnificient-brick', displayName: 'Magnificient Brick', type: 'craftable', tier: Tier.T9 },
  { id: 'refined-magnificient-brick', displayName: 'Refined Magnificient Brick', type: 'craftable', tier: Tier.T9 },
  { id: 'unfired-magnificient-brick', displayName: 'Unfired Magnificient Brick', type: 'craftable', tier: Tier.T9 },
  { id: 'flawless-brick', displayName: 'Flawless Brick', type: 'craftable', tier: Tier.T10 },
  { id: 'refined-flawless-brick', displayName: 'Refined Flawless Brick', type: 'craftable', tier: Tier.T10 },
  { id: 'unfired-flawless-brick', displayName: 'Unfired Flawless Brick', type: 'craftable', tier: Tier.T10 },
];
