import {ItemNode, Tier} from '../item-node';

export const items: ItemNode[] = [
  {id: 'basic-healing-potion', displayName: 'Basic Healing Potion', type: 'craftable', tier: Tier.T1},
  {id: 'basic-potters-mix', displayName: 'Basic Potter\'s Mix', type: 'craftable', tier: Tier.T1},
  {id: 'basic-stamina-potion', displayName: 'Basic Stamina Potion', type: 'craftable', tier: Tier.T1},
  {id: 'cooking-pot', displayName: 'Cooking Pot', type: 'craftable', tier: Tier.T1},
  {id: 'simple-healing-potion', displayName: 'Simple Healing Potion', type: 'craftable', tier: Tier.T2},
  {id: 'simple-potters-mix', displayName: 'Simple Potter\'s Mix', type: 'craftable', tier: Tier.T2},
  {id: 'simple-stamina-potion', displayName: 'Simple Stamina Potion', type: 'craftable', tier: Tier.T2},
  {id: 'infused-healing-potion', displayName: 'Infused Healing Potion', type: 'craftable', tier: Tier.T3},
  {id: 'infused-potters-mix', displayName: 'Infused Potter\'s Mix', type: 'craftable', tier: Tier.T3},
  {id: 'infused-stamina-potion', displayName: 'Infused Stamina Potion', type: 'craftable', tier: Tier.T3},
  {id: 'fine-healing-potion', displayName: 'Fine Healing Potion', type: 'craftable', tier: Tier.T4},
  {id: 'fine-potters-mix', displayName: 'Fine Potter\'s Mix', type: 'craftable', tier: Tier.T4},
  {id: 'fine-stamina-potion', displayName: 'Fine Stamina Potion', type: 'craftable', tier: Tier.T4},
  {id: 'exquisite-healing-potion', displayName: 'Exquisite Healing Potion', type: 'craftable', tier: Tier.T5},
  {id: 'exquisite-potters-mix', displayName: 'Exquisite Potter\'s Mix', type: 'craftable', tier: Tier.T5},
  {id: 'exquisite-stamina-potion', displayName: 'Exquisite Stamina Potion', type: 'craftable', tier: Tier.T5},
  {id: 'peerless-healing-potion', displayName: 'Peerless Healing Potion', type: 'craftable', tier: Tier.T6},
  {id: 'peerless-potters-mix', displayName: 'Peerless Potter\'s Mix', type: 'craftable', tier: Tier.T6},
  {id: 'peerless-stamina-potion', displayName: 'Peerless Stamina Potion', type: 'craftable', tier: Tier.T6},
  {id: 'ornate-healing-potion', displayName: 'Ornate Healing Potion', type: 'craftable', tier: Tier.T7},
  {id: 'ornate-potters-mix', displayName: 'Ornate Potter\'s Mix', type: 'craftable', tier: Tier.T7},
  {id: 'ornate-stamina-potion', displayName: 'Ornate Stamina Potion', type: 'craftable', tier: Tier.T7},
  {id: 'pristine-healing-potion', displayName: 'Pristine Healing Potion', type: 'craftable', tier: Tier.T8},
  {id: 'pristine-potters-mix', displayName: 'Pristine Potter\'s Mix', type: 'craftable', tier: Tier.T8},
  {id: 'pristine-stamina-potion', displayName: 'Pristine Stamina Potion', type: 'craftable', tier: Tier.T8},
  {id: 'magnificient-healing-potion', displayName: 'Magnificient Healing Potion', type: 'craftable', tier: Tier.T9},
  {id: 'magnificient-potters-mix', displayName: 'Magnificient Potter\'s Mix', type: 'craftable', tier: Tier.T9},
  {id: 'magnificient-stamina-potion', displayName: 'Magnificient Stamina Potion', type: 'craftable', tier: Tier.T9},
  {id: 'flawless-healing-potion', displayName: 'Flawless Healing Potion', type: 'craftable', tier: Tier.T10},
  {id: 'flawless-potters-mix', displayName: 'Flawless Potter\'s Mix', type: 'craftable', tier: Tier.T10},
  {id: 'flawless-stamina-potion', displayName: 'Flawless Stamina Potion', type: 'craftable', tier: Tier.T10},
];
