import { ItemNode, Tier } from '../item-node';

export const items: ItemNode[] = [
  { id: 'basic-bait-and-shells', displayName: 'Basic Bait and Shells', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-crop-oil', displayName: 'Basic Crop Oil', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-fish-oil', displayName: 'Basic Fish Oil', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-meat-experiment', displayName: 'Basic Meat Experiment', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-raw-meat', displayName: 'Basic Raw Meat', type: 'gatherable', tier: Tier.T1 },
  { id: 'crushed-rough-shells', displayName: 'Crushed Rough Shells', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-deluxe-meat-sandwich', displayName: 'Plain Deluxe Meat Sandwich', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-deluxe-ocean-fish-sticks', displayName: 'Plain Deluxe Ocean Fish Sticks', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-meat-sandwich', displayName: 'Plain Meat Sandwich', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-ocean-fish-sticks', displayName: 'Plain Ocean Fish Sticks', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-roasted-fish', displayName: 'Plain Roasted Fish', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-roasted-meat', displayName: 'Plain Roasted Meat', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-roasted-ocean-fish', displayName: 'Plain Roasted Ocean Fish', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-skewered-baitfish', displayName: 'Plain Skewered Baitfish', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-cleaned-pelt', displayName: 'Rough Cleaned Pelt', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-dried-pelt', displayName: 'Rough Dried Pelt', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-raw-pelt', displayName: 'Rough Raw Pelt', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-shell', displayName: 'Rough Shell', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-tanned-pelt', displayName: 'Rough Tanned Pelt', type: 'gatherable', tier: Tier.T1 },
  { id: 'crushed-simple-shells', displayName: 'Crushed Simple Shells', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-deluxe-meat-sandwich', displayName: 'Savory Deluxe Meat Sandwich', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-deluxe-ocean-fish-sticks', displayName: 'Savory Deluxe Ocean Fish Sticks', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-meat-sandwich', displayName: 'Savory Meat Sandwich', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-ocean-fish-sticks', displayName: 'Savory Ocean Fish Sticks', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-roasted-fish', displayName: 'Savory Roasted Fish', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-roasted-meat', displayName: 'Savory Roasted Meat', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-roasted-ocean-fish', displayName: 'Savory Roasted Ocean Fish', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-skewered-baitfish', displayName: 'Savory Skewered Baitfish', type: 'gatherable', tier: Tier.T2 },
  { id: 'serpentfish-experiment', displayName: 'Serpentfish Experiment', type: 'gatherable', tier: Tier.T2 },
  { id: 'serpentfish-filet', displayName: 'Serpentfish Filet', type: 'gatherable', tier: Tier.T2 },
  { id: 'serpentfish-products', displayName: 'Serpentfish Products', type: 'gatherable', tier: Tier.T2 },
  { id: 'serpentfish-scale', displayName: 'Serpentfish Scale', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-bait-and-shells', displayName: 'Simple Bait and Shells', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-cleaned-pelt', displayName: 'Simple Cleaned Pelt', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-crop-oil', displayName: 'Simple Crop Oil', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-dried-pelt', displayName: 'Simple Dried Pelt', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-fish-oil', displayName: 'Simple Fish Oil', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-meat-experiment', displayName: 'Simple Meat Experiment', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-raw-meat', displayName: 'Simple Raw Meat', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-raw-pelt', displayName: 'Simple Raw Pelt', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-shell', displayName: 'Simple Shell', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-tanned-pelt', displayName: 'Simple Tanned Pelt', type: 'gatherable', tier: Tier.T2 },
  { id: 't2-baitfish-output', displayName: 'T2 Baitfish Output', type: 'gatherable', tier: Tier.T2 },
  { id: 't2-lakefish-output', displayName: 'T2 Lakefish Output', type: 'gatherable', tier: Tier.T2 },
  { id: 't2-oceanfish-output', displayName: 'T2 Oceanfish Output', type: 'gatherable', tier: Tier.T2 },
  { id: 't2-seashell-output', displayName: 'T2 Seashell Output', type: 'gatherable', tier: Tier.T2 },
  { id: 'crushed-sturdy-shells', displayName: 'Crushed Sturdy Shells', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-bait-and-shells', displayName: 'Infused Bait and Shells', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-crop-oil', displayName: 'Infused Crop Oil', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-fish-oil', displayName: 'Infused Fish Oil', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-meat-experiment', displayName: 'Infused Meat Experiment', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-raw-meat', displayName: 'Infused Raw Meat', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-cleaned-pelt', displayName: 'Sturdy Cleaned Pelt', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-dried-pelt', displayName: 'Sturdy Dried Pelt', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-raw-pelt', displayName: 'Sturdy Raw Pelt', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-shell', displayName: 'Sturdy Shell', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-tanned-pelt', displayName: 'Sturdy Tanned Pelt', type: 'gatherable', tier: Tier.T3 },
  { id: 't3-baitfish-output', displayName: 'T3 Baitfish Output', type: 'gatherable', tier: Tier.T3 },
  { id: 't3-lakefish-output', displayName: 'T3 Lakefish Output', type: 'gatherable', tier: Tier.T3 },
  { id: 't3-oceanfish-output', displayName: 'T3 Oceanfish Output', type: 'gatherable', tier: Tier.T3 },
  { id: 't3-seashell-output', displayName: 'T3 Seashell Output', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-deluxe-meat-sandwich', displayName: 'Zesty Deluxe Meat Sandwich', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-deluxe-ocean-fish-sticks', displayName: 'Zesty Deluxe Ocean Fish Sticks', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-meat-sandwich', displayName: 'Zesty Meat Sandwich', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-ocean-fish-sticks', displayName: 'Zesty Ocean Fish Sticks', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-roasted-fish', displayName: 'Zesty Roasted Fish', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-roasted-meat', displayName: 'Zesty Roasted Meat', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-roasted-ocean-fish', displayName: 'Zesty Roasted Ocean Fish', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-skewered-baitfish', displayName: 'Zesty Skewered Baitfish', type: 'gatherable', tier: Tier.T3 },
  { id: 'crushed-fine-shells', displayName: 'Crushed Fine Shells', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-bait-and-shells', displayName: 'Fine Bait and Shells', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-cleaned-pelt', displayName: 'Fine Cleaned Pelt', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-crop-oil', displayName: 'Fine Crop Oil', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-deluxe-meat-sandwich', displayName: 'Fine Deluxe Meat Sandwich', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-deluxe-ocean-fish-sticks', displayName: 'Fine Deluxe Ocean Fish Sticks', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-dried-pelt', displayName: 'Fine Dried Pelt', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-fish-oil', displayName: 'Fine Fish Oil', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-meat-experiment', displayName: 'Fine Meat Experiment', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-meat-sandwich', displayName: 'Fine Meat Sandwich', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-ocean-fish-sticks', displayName: 'Fine Ocean Fish Sticks', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-raw-meat', displayName: 'Fine Raw Meat', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-raw-pelt', displayName: 'Fine Raw Pelt', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-roasted-fish', displayName: 'Fine Roasted Fish', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-roasted-meat', displayName: 'Fine Roasted Meat', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-roasted-ocean-fish', displayName: 'Fine Roasted Ocean Fish', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-shell', displayName: 'Fine Shell', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-skewered-baitfish', displayName: 'Fine Skewered Baitfish', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-tanned-pelt', displayName: 'Fine Tanned Pelt', type: 'gatherable', tier: Tier.T4 },
  { id: 't4-baitfish-output', displayName: 'T4 Baitfish Output', type: 'gatherable', tier: Tier.T4 },
  { id: 't4-lakefish-output', displayName: 'T4 Lakefish Output', type: 'gatherable', tier: Tier.T4 },
  { id: 't4-oceanfish-output', displayName: 'T4 Oceanfish Output', type: 'gatherable', tier: Tier.T4 },
  { id: 't4-seashell-output', displayName: 'T4 Seashell Output', type: 'gatherable', tier: Tier.T4 },
  { id: 'crushed-exquisite-shells', displayName: 'Crushed Exquisite Shells', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-bait-and-shells', displayName: 'Exquisite Bait and Shells', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-cleaned-pelt', displayName: 'Exquisite Cleaned Pelt', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-crop-oil', displayName: 'Exquisite Crop Oil', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-dried-pelt', displayName: 'Exquisite Dried Pelt', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-fish-oil', displayName: 'Exquisite Fish Oil', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-meat-experiment', displayName: 'Exquisite Meat Experiment', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-raw-meat', displayName: 'Exquisite Raw Meat', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-raw-pelt', displayName: 'Exquisite Raw Pelt', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-shell', displayName: 'Exquisite Shell', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-tanned-pelt', displayName: 'Exquisite Tanned Pelt', type: 'gatherable', tier: Tier.T5 },
  { id: 'golden-crawfish', displayName: 'Golden Crawfish', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-deluxe-meat-sandwich', displayName: 'Succulent Deluxe Meat Sandwich', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-deluxe-ocean-fish-sticks', displayName: 'Succulent Deluxe Ocean Fish Sticks', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-meat-sandwich', displayName: 'Succulent Meat Sandwich', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-ocean-fish-sticks', displayName: 'Succulent Ocean Fish Sticks', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-roasted-fish', displayName: 'Succulent Roasted Fish', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-roasted-meat', displayName: 'Succulent Roasted Meat', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-roasted-ocean-fish', displayName: 'Succulent Roasted Ocean Fish', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-skewered-baitfish', displayName: 'Succulent Skewered Baitfish', type: 'gatherable', tier: Tier.T5 },
  { id: 't5-baitfish-output', displayName: 'T5 Baitfish Output', type: 'gatherable', tier: Tier.T5 },
  { id: 't5-lakefish-output', displayName: 'T5 Lakefish Output', type: 'gatherable', tier: Tier.T5 },
  { id: 't5-oceanfish-output', displayName: 'T5 Oceanfish Output', type: 'gatherable', tier: Tier.T5 },
  { id: 't5-seashell-output', displayName: 'T5 Seashell Output', type: 'gatherable', tier: Tier.T5 },
  { id: 'abyssal-swordfish-experiment', displayName: 'Abyssal Swordfish Experiment', type: 'gatherable', tier: Tier.T6 },
  { id: 'abyssal-swordfish-filet', displayName: 'Abyssal Swordfish Filet', type: 'gatherable', tier: Tier.T6 },
  { id: 'abyssal-swordfish-products', displayName: 'Abyssal Swordfish Products', type: 'gatherable', tier: Tier.T6 },
  { id: 'abyssal-swordfish-scale', displayName: 'Abyssal Swordfish Scale', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-deluxe-meat-sandwich', displayName: 'Ambrosial Deluxe Meat Sandwich', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-deluxe-ocean-fish-sticks', displayName: 'Ambrosial Deluxe Ocean Fish Sticks', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-meat-sandwich', displayName: 'Ambrosial Meat Sandwich', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-ocean-fish-sticks', displayName: 'Ambrosial Ocean Fish Sticks', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-roasted-fish', displayName: 'Ambrosial Roasted Fish', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-roasted-meat', displayName: 'Ambrosial Roasted Meat', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-roasted-ocean-fish', displayName: 'Ambrosial Roasted Ocean Fish', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-skewered-baitfish', displayName: 'Ambrosial Skewered Baitfish', type: 'gatherable', tier: Tier.T6 },
  { id: 'crushed-peerless-shells', displayName: 'Crushed Peerless Shells', type: 'gatherable', tier: Tier.T6 },
  { id: 'ornate-bait-and-shells', displayName: 'Ornate Bait and Shells', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-bait-and-shells', displayName: 'Peerless Bait and Shells', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-cleaned-pelt', displayName: 'Peerless Cleaned Pelt', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-crop-oil', displayName: 'Peerless Crop Oil', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-dried-pelt', displayName: 'Peerless Dried Pelt', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-fish-oil', displayName: 'Peerless Fish Oil', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-meat-experiment', displayName: 'Peerless Meat Experiment', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-raw-meat', displayName: 'Peerless Raw Meat', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-raw-pelt', displayName: 'Peerless Raw Pelt', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-shell', displayName: 'Peerless Shell', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-tanned-pelt', displayName: 'Peerless Tanned Pelt', type: 'gatherable', tier: Tier.T6 },
  { id: 't6-baitfish-output', displayName: 'T6 Baitfish Output', type: 'gatherable', tier: Tier.T6 },
  { id: 't6-lakefish-output', displayName: 'T6 Lakefish Output', type: 'gatherable', tier: Tier.T6 },
  { id: 't6-oceanfish-output', displayName: 'T6 Oceanfish Output', type: 'gatherable', tier: Tier.T6 },
  { id: 't6-seashell-output', displayName: 'T6 Seashell Output', type: 'gatherable', tier: Tier.T6 },
  { id: 'crushed-ornate-shells', displayName: 'Crushed Ornate Shells', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-cleaned-pelt', displayName: 'Ornate Cleaned Pelt', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-crop-oil', displayName: 'Ornate Crop Oil', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-fish-oil', displayName: 'Ornate Fish Oil', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-raw-meat', displayName: 'Ornate Raw Meat', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-raw-pelt', displayName: 'Ornate Raw Pelt', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-shell', displayName: 'Ornate Shell', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-tanned-pelt', displayName: 'Ornate Tanned Pelt', type: 'gatherable', tier: Tier.T7 },
  { id: 't7-baitfish-output', displayName: 'T7 Baitfish Output', type: 'gatherable', tier: Tier.T7 },
  { id: 't7-lakefish-output', displayName: 'T7 Lakefish Output', type: 'gatherable', tier: Tier.T7 },
  { id: 't7-seashell-output', displayName: 'T7 Seashell Output', type: 'gatherable', tier: Tier.T7 },
  { id: 'crushed-pristine-shells', displayName: 'Crushed Pristine Shells', type: 'gatherable', tier: Tier.T8 },
  { id: 'mysterious-anglerfish-filet', displayName: 'Mysterious Anglerfish Filet', type: 'gatherable', tier: Tier.T8 },
  { id: 'mysterious-anglerfish-products', displayName: 'Mysterious Anglerfish Products', type: 'gatherable', tier: Tier.T8 },
  { id: 'mysterious-anglerfish-scale', displayName: 'Mysterious Anglerfish Scale', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-bait-and-shells', displayName: 'Pristine Bait and Shells', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-cleaned-pelt', displayName: 'Pristine Cleaned Pelt', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-crop-oil', displayName: 'Pristine Crop Oil', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-fish-oil', displayName: 'Pristine Fish Oil', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-raw-meat', displayName: 'Pristine Raw Meat', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-raw-pelt', displayName: 'Pristine Raw Pelt', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-shell', displayName: 'Pristine Shell', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-tanned-pelt', displayName: 'Pristine Tanned Pelt', type: 'gatherable', tier: Tier.T8 },
  { id: 't8-baitfish-output', displayName: 'T8 Baitfish Output', type: 'gatherable', tier: Tier.T8 },
  { id: 't8-lakefish-output', displayName: 'T8 Lakefish Output', type: 'gatherable', tier: Tier.T8 },
  { id: 't8-seashell-output', displayName: 'T8 Seashell Output', type: 'gatherable', tier: Tier.T8 },
  { id: 'crushed-magnificient-shells', displayName: 'Crushed Magnificient Shells', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-bait-and-shells', displayName: 'Magnificient Bait and Shells', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-baitfish', displayName: 'Magnificient Baitfish', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-cleaned-pelt', displayName: 'Magnificient Cleaned Pelt', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-crop-oil', displayName: 'Magnificient Crop Oil', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-fish-oil', displayName: 'Magnificient Fish Oil', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-lake-fish-filet', displayName: 'Magnificient Lake Fish Filet', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-lake-fish-products', displayName: 'Magnificient Lake Fish Products', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-lakefish', displayName: 'Magnificient Lakefish', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-ocean-fish-filet', displayName: 'Magnificient Ocean Fish Filet', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-ocean-fish-products', displayName: 'Magnificient Ocean Fish Products', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-ocean-fish-scale', displayName: 'Magnificient Ocean Fish Scale', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-raw-meat', displayName: 'Magnificient Raw Meat', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-raw-pelt', displayName: 'Magnificient Raw Pelt', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-shell', displayName: 'Magnificient Shell', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-tanned-pelt', displayName: 'Magnificient Tanned Pelt', type: 'gatherable', tier: Tier.T9 },
  { id: 't9-baitfish-output', displayName: 'T9 Baitfish Output', type: 'gatherable', tier: Tier.T9 },
  { id: 't9-lakefish-output', displayName: 'T9 Lakefish Output', type: 'gatherable', tier: Tier.T9 },
  { id: 'crushed-flawless-shells', displayName: 'Crushed Flawless Shells', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-bait-and-shells', displayName: 'Flawless Bait and Shells', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-baitfish', displayName: 'Flawless Baitfish', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-cleaned-pelt', displayName: 'Flawless Cleaned Pelt', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-crop-oil', displayName: 'Flawless Crop Oil', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-fish-oil', displayName: 'Flawless Fish Oil', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-lake-fish-filet', displayName: 'Flawless Lake Fish Filet', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-lake-fish-products', displayName: 'Flawless Lake Fish Products', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-lakefish', displayName: 'Flawless Lakefish', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-ocean-fish-filet', displayName: 'Flawless Ocean Fish Filet', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-ocean-fish-products', displayName: 'Flawless Ocean Fish Products', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-ocean-fish-scale', displayName: 'Flawless Ocean Fish Scale', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-raw-meat', displayName: 'Flawless Raw Meat', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-raw-pelt', displayName: 'Flawless Raw Pelt', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-shell', displayName: 'Flawless Shell', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-tanned-pelt', displayName: 'Flawless Tanned Pelt', type: 'gatherable', tier: Tier.T10 },
  { id: 't10-baitfish-output', displayName: 'T10 Baitfish Output', type: 'gatherable', tier: Tier.T10 },
  { id: 't10-lakefish-output', displayName: 'T10 Lakefish Output', type: 'gatherable', tier: Tier.T10 },
];
