import { ItemNode, Tier } from '../item-node';

export const items: ItemNode[] = [
  { id: 'beginners-stone-carvings', displayName: 'Beginner\'s Stone Carvings', type: 'gatherable', tier: Tier.T1 },
  { id: 'beginners-stone-diagram-research', displayName: 'Beginner\'s Stone Diagram Research', type: 'gatherable', tier: Tier.T1 },
  { id: 'beginners-stone-diagrams', displayName: 'Beginner\'s Stone Diagrams', type: 'gatherable', tier: Tier.T1 },
  { id: 'beginners-stone-research', displayName: 'Beginner\'s Stone Research', type: 'gatherable', tier: Tier.T1 },
  { id: 'crushed-ferralith-ore', displayName: 'Crushed Ferralith Ore', type: 'gatherable', tier: Tier.T1 },
  { id: 'crushed-ferralith-ore-output', displayName: 'Crushed Ferralith Ore Output', type: 'gatherable', tier: Tier.T1 },
  { id: 'ferralith-claymore', displayName: 'Ferralith Claymore', type: 'gatherable', tier: Tier.T1 },
  { id: 'ferralith-ore-concentrate', displayName: 'Ferralith Ore Concentrate', type: 'gatherable', tier: Tier.T1 },
  { id: 'ferralith-ore-piece', displayName: 'Ferralith Ore Piece', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-foresters-pot', displayName: 'Rough Forester\'s Pot', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-gem', displayName: 'Rough Gem', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-gem-dust', displayName: 'Rough Gem Dust', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-gem-encrusted-ring', displayName: 'Rough Gem Encrusted Ring', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-gem-fragments', displayName: 'Rough Gem Fragments', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-pebbles', displayName: 'Rough Pebbles', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-pebbles-output', displayName: 'Rough Pebbles Output', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-rock', displayName: 'Rough Rock', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-unfired-foresters-pot', displayName: 'Rough Unfired Forester\'s Pot', type: 'gatherable', tier: Tier.T1 },
  { id: 'stone-brazier-blueprint', displayName: 'Stone Brazier Blueprint', type: 'gatherable', tier: Tier.T1 },
  { id: 'crushed-pyrelite-ore', displayName: 'Crushed Pyrelite Ore', type: 'gatherable', tier: Tier.T2 },
  { id: 'crushed-pyrelite-ore-output', displayName: 'Crushed Pyrelite Ore Output', type: 'gatherable', tier: Tier.T2 },
  { id: 'novice-stone-carvings', displayName: 'Novice Stone Carvings', type: 'gatherable', tier: Tier.T2 },
  { id: 'novice-stone-diagram-research', displayName: 'Novice Stone Diagram Research', type: 'gatherable', tier: Tier.T2 },
  { id: 'novice-stone-diagrams', displayName: 'Novice Stone Diagrams', type: 'gatherable', tier: Tier.T2 },
  { id: 'novices-stone-research', displayName: 'Novice\'s Stone Research', type: 'gatherable', tier: Tier.T2 },
  { id: 'pyrelite-claymore', displayName: 'Pyrelite Claymore', type: 'gatherable', tier: Tier.T2 },
  { id: 'pyrelite-ore-concentrate', displayName: 'Pyrelite Ore Concentrate', type: 'gatherable', tier: Tier.T2 },
  { id: 'pyrelite-ore-piece', displayName: 'Pyrelite Ore Piece', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-foresters-pot', displayName: 'Simple Forester\'s Pot', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-gem', displayName: 'Simple Gem', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-gem-dust', displayName: 'Simple Gem Dust', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-gem-encrusted-ring', displayName: 'Simple Gem Encrusted Ring', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-gem-fragments', displayName: 'Simple Gem Fragments', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-pebbles', displayName: 'Simple Pebbles', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-pebbles-output', displayName: 'Simple Pebbles Output', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-rock', displayName: 'Simple Rock', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-unfired-foresters-pot', displayName: 'Simple Unfired Forester\'s Pot', type: 'gatherable', tier: Tier.T2 },
  { id: 't2-ore-output', displayName: 'T2 Ore Output', type: 'gatherable', tier: Tier.T2 },
  { id: 't2-rock-output', displayName: 'T2 Rock Output', type: 'gatherable', tier: Tier.T2 },
  { id: 'crushed-emarium-ore', displayName: 'Crushed Emarium Ore', type: 'gatherable', tier: Tier.T3 },
  { id: 'crushed-emarium-ore-output', displayName: 'Crushed Emarium Ore Output', type: 'gatherable', tier: Tier.T3 },
  { id: 'emarium-claymore', displayName: 'Emarium Claymore', type: 'gatherable', tier: Tier.T3 },
  { id: 'emarium-ore-concentrate', displayName: 'Emarium Ore Concentrate', type: 'gatherable', tier: Tier.T3 },
  { id: 'emarium-ore-piece', displayName: 'Emarium Ore Piece', type: 'gatherable', tier: Tier.T3 },
  { id: 'essential-stone-carvings', displayName: 'Essential Stone Carvings', type: 'gatherable', tier: Tier.T3 },
  { id: 'essential-stone-diagram-research', displayName: 'Essential Stone Diagram Research', type: 'gatherable', tier: Tier.T3 },
  { id: 'essential-stone-diagrams', displayName: 'Essential Stone Diagrams', type: 'gatherable', tier: Tier.T3 },
  { id: 'essential-stone-research', displayName: 'Essential Stone Research', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-gem-dust', displayName: 'Infused Gem Dust', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-foresters-pot', displayName: 'Sturdy Forester\'s Pot', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-gem', displayName: 'Sturdy Gem', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-gem-encrusted-ring', displayName: 'Sturdy Gem Encrusted Ring', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-gem-fragments', displayName: 'Sturdy Gem Fragments', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-pebbles', displayName: 'Sturdy Pebbles', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-pebbles-output', displayName: 'Sturdy Pebbles Output', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-rock', displayName: 'Sturdy Rock', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-unfired-foresters-pot', displayName: 'Sturdy Unfired Forester\'s Pot', type: 'gatherable', tier: Tier.T3 },
  { id: 't3-ore-output', displayName: 'T3 Ore Output', type: 'gatherable', tier: Tier.T3 },
  { id: 't3-rock-output', displayName: 'T3 Rock Output', type: 'gatherable', tier: Tier.T3 },
  { id: 'crushed-elenvar-ore', displayName: 'Crushed Elenvar Ore', type: 'gatherable', tier: Tier.T4 },
  { id: 'crushed-elenvar-ore-output', displayName: 'Crushed Elenvar Ore Output', type: 'gatherable', tier: Tier.T4 },
  { id: 'elenvar-claymore', displayName: 'Elenvar Claymore', type: 'gatherable', tier: Tier.T4 },
  { id: 'elenvar-ore-concentrate', displayName: 'Elenvar Ore Concentrate', type: 'gatherable', tier: Tier.T4 },
  { id: 'elenvar-ore-piece', displayName: 'Elenvar Ore Piece', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-foresters-pot', displayName: 'Fine Forester\'s Pot', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-gem', displayName: 'Fine Gem', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-gem-dust', displayName: 'Fine Gem Dust', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-gem-encrusted-ring', displayName: 'Fine Gem Encrusted Ring', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-gem-fragments', displayName: 'Fine Gem Fragments', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-pebbles', displayName: 'Fine Pebbles', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-pebbles-output', displayName: 'Fine Pebbles Output', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-rock', displayName: 'Fine Rock', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-unfired-foresters-pot', displayName: 'Fine Unfired Forester\'s Pot', type: 'gatherable', tier: Tier.T4 },
  { id: 'proficient-stone-carvings', displayName: 'Proficient Stone Carvings', type: 'gatherable', tier: Tier.T4 },
  { id: 'proficient-stone-diagram-research', displayName: 'Proficient Stone Diagram Research', type: 'gatherable', tier: Tier.T4 },
  { id: 'proficient-stone-diagrams', displayName: 'Proficient Stone Diagrams', type: 'gatherable', tier: Tier.T4 },
  { id: 'proficient-stone-research', displayName: 'Proficient Stone Research', type: 'gatherable', tier: Tier.T4 },
  { id: 't4-ore-output', displayName: 'T4 Ore Output', type: 'gatherable', tier: Tier.T4 },
  { id: 't4-rock-output', displayName: 'T4 Rock Output', type: 'gatherable', tier: Tier.T4 },
  { id: 'advanced-stone-carvings', displayName: 'Advanced Stone Carvings', type: 'gatherable', tier: Tier.T5 },
  { id: 'advanced-stone-diagram-research', displayName: 'Advanced Stone Diagram Research', type: 'gatherable', tier: Tier.T5 },
  { id: 'advanced-stone-diagrams', displayName: 'Advanced Stone Diagrams', type: 'gatherable', tier: Tier.T5 },
  { id: 'advanced-stone-research', displayName: 'Advanced Stone Research', type: 'gatherable', tier: Tier.T5 },
  { id: 'crushed-luminite-ore', displayName: 'Crushed Luminite Ore', type: 'gatherable', tier: Tier.T5 },
  { id: 'crushed-luminite-ore-output', displayName: 'Crushed Luminite Ore Output', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-foresters-pot', displayName: 'Exquisite Forester\'s Pot', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-gem', displayName: 'Exquisite Gem', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-gem-dust', displayName: 'Exquisite Gem Dust', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-gem-encrusted-ring', displayName: 'Exquisite Gem Encrusted Ring', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-gem-fragments', displayName: 'Exquisite Gem Fragments', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-pebbles', displayName: 'Exquisite Pebbles', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-pebbles-output', displayName: 'Exquisite Pebbles Output', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-rock', displayName: 'Exquisite Rock', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-unfired-foresters-pot', displayName: 'Exquisite Unfired Forester\'s Pot', type: 'gatherable', tier: Tier.T5 },
  { id: 'luminite-claymore', displayName: 'Luminite Claymore', type: 'gatherable', tier: Tier.T5 },
  { id: 'luminite-ore-concentrate', displayName: 'Luminite Ore Concentrate', type: 'gatherable', tier: Tier.T5 },
  { id: 'luminite-ore-piece', displayName: 'Luminite Ore Piece', type: 'gatherable', tier: Tier.T5 },
  { id: 't5-ore-output', displayName: 'T5 Ore Output', type: 'gatherable', tier: Tier.T5 },
  { id: 't5-rock-output', displayName: 'T5 Rock Output', type: 'gatherable', tier: Tier.T5 },
  { id: 'comprehensive-stone-carvings', displayName: 'Comprehensive Stone Carvings', type: 'gatherable', tier: Tier.T6 },
  { id: 'comprehensive-stone-diagram-research', displayName: 'Comprehensive Stone Diagram Research', type: 'gatherable', tier: Tier.T6 },
  { id: 'comprehensive-stone-diagrams', displayName: 'Comprehensive Stone Diagrams', type: 'gatherable', tier: Tier.T6 },
  { id: 'comprehensive-stone-research', displayName: 'Comprehensive Stone Research', type: 'gatherable', tier: Tier.T6 },
  { id: 'crushed-rathium-ore', displayName: 'Crushed Rathium Ore', type: 'gatherable', tier: Tier.T6 },
  { id: 'crushed-rathium-ore-output', displayName: 'Crushed Rathium Ore Output', type: 'gatherable', tier: Tier.T6 },
  { id: 'left-power-core', displayName: 'Left Power Core', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-foresters-pot', displayName: 'Peerless Forester\'s Pot', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-gem', displayName: 'Peerless Gem', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-gem-dust', displayName: 'Peerless Gem Dust', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-gem-encrusted-ring', displayName: 'Peerless Gem Encrusted Ring', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-gem-fragments', displayName: 'Peerless Gem Fragments', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-pebbles', displayName: 'Peerless Pebbles', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-pebbles-output', displayName: 'Peerless Pebbles Output', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-rock', displayName: 'Peerless Rock', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-unfired-foresters-pot', displayName: 'Peerless Unfired Forester\'s Pot', type: 'gatherable', tier: Tier.T6 },
  { id: 'rathium-claymore', displayName: 'Rathium Claymore', type: 'gatherable', tier: Tier.T6 },
  { id: 'rathium-ore-concentrate', displayName: 'Rathium Ore Concentrate', type: 'gatherable', tier: Tier.T6 },
  { id: 'rathium-ore-piece', displayName: 'Rathium Ore Piece', type: 'gatherable', tier: Tier.T6 },
  { id: 'right-power-core', displayName: 'Right Power Core', type: 'gatherable', tier: Tier.T6 },
  { id: 't6-ore-output', displayName: 'T6 Ore Output', type: 'gatherable', tier: Tier.T6 },
  { id: 't6-rock-output', displayName: 'T6 Rock Output', type: 'gatherable', tier: Tier.T6 },
  { id: 'aurumite-claymore', displayName: 'Aurumite Claymore', type: 'gatherable', tier: Tier.T7 },
  { id: 'aurumite-ore-concentrate', displayName: 'Aurumite Ore Concentrate', type: 'gatherable', tier: Tier.T7 },
  { id: 'aurumite-ore-piece', displayName: 'Aurumite Ore Piece', type: 'gatherable', tier: Tier.T7 },
  { id: 'crushed-aurumite-ore', displayName: 'Crushed Aurumite Ore', type: 'gatherable', tier: Tier.T7 },
  { id: 'crushed-aurumite-ore-output', displayName: 'Crushed Aurumite Ore Output', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-foresters-pot', displayName: 'Ornate Forester\'s Pot', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-gem', displayName: 'Ornate Gem', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-gem-encrusted-ring', displayName: 'Ornate Gem Encrusted Ring', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-gem-fragments', displayName: 'Ornate Gem Fragments', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-pebbles', displayName: 'Ornate Pebbles', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-pebbles-output', displayName: 'Ornate Pebbles Output', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-rock', displayName: 'Ornate Rock', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-stone-carvings', displayName: 'Ornate Stone Carvings', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-stone-research', displayName: 'Ornate Stone Research', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-unfired-foresters-pot', displayName: 'Ornate Unfired Forester\'s Pot', type: 'gatherable', tier: Tier.T7 },
  { id: 't7-rock-output', displayName: 'T7 Rock Output', type: 'gatherable', tier: Tier.T7 },
  { id: 'celestium-claymore', displayName: 'Celestium Claymore', type: 'gatherable', tier: Tier.T8 },
  { id: 'celestium-ore-concentrate', displayName: 'Celestium Ore Concentrate', type: 'gatherable', tier: Tier.T8 },
  { id: 'celestium-ore-piece', displayName: 'Celestium Ore Piece', type: 'gatherable', tier: Tier.T8 },
  { id: 'crushed-celestium-ore', displayName: 'Crushed Celestium Ore', type: 'gatherable', tier: Tier.T8 },
  { id: 'crushed-celestium-ore-output', displayName: 'Crushed Celestium Ore Output', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-foresters-pot', displayName: 'Pristine Forester\'s Pot', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-gem', displayName: 'Pristine Gem', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-gem-encrusted-ring', displayName: 'Pristine Gem Encrusted Ring', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-gem-fragments', displayName: 'Pristine Gem Fragments', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-pebbles', displayName: 'Pristine Pebbles', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-pebbles-output', displayName: 'Pristine Pebbles Output', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-rock', displayName: 'Pristine Rock', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-stone-carvings', displayName: 'Pristine Stone Carvings', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-stone-research', displayName: 'Pristine Stone Research', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-unfired-foresters-pot', displayName: 'Pristine Unfired Forester\'s Pot', type: 'gatherable', tier: Tier.T8 },
  { id: 't8-rock-output', displayName: 'T8 Rock Output', type: 'gatherable', tier: Tier.T8 },
  { id: 'crushed-umbracite-ore', displayName: 'Crushed Umbracite Ore', type: 'gatherable', tier: Tier.T9 },
  { id: 'crushed-umbracite-ore-output', displayName: 'Crushed Umbracite Ore Output', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-foresters-pot', displayName: 'Magnificient Forester\'s Pot', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-gem', displayName: 'Magnificient Gem', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-gem-encrusted-ring', displayName: 'Magnificient Gem Encrusted Ring', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-gem-fragments', displayName: 'Magnificient Gem Fragments', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-pebbles', displayName: 'Magnificient Pebbles', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-pebbles-output', displayName: 'Magnificient Pebbles Output', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-rock', displayName: 'Magnificient Rock', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-stone-carvings', displayName: 'Magnificient Stone Carvings', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-stone-research', displayName: 'Magnificient Stone Research', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-unfired-foresters-pot', displayName: 'Magnificient Unfired Forester\'s Pot', type: 'gatherable', tier: Tier.T9 },
  { id: 'umbracite-claymore', displayName: 'Umbracite Claymore', type: 'gatherable', tier: Tier.T9 },
  { id: 'umbracite-ore-concentrate', displayName: 'Umbracite Ore Concentrate', type: 'gatherable', tier: Tier.T9 },
  { id: 'umbracite-ore-piece', displayName: 'Umbracite Ore Piece', type: 'gatherable', tier: Tier.T9 },
  { id: 'astralite-claymore', displayName: 'Astralite Claymore', type: 'gatherable', tier: Tier.T10 },
  { id: 'astralite-ore-concentrate', displayName: 'Astralite Ore Concentrate', type: 'gatherable', tier: Tier.T10 },
  { id: 'astralite-ore-piece', displayName: 'Astralite Ore Piece', type: 'gatherable', tier: Tier.T10 },
  { id: 'crushed-astralite-ore', displayName: 'Crushed Astralite Ore', type: 'gatherable', tier: Tier.T10 },
  { id: 'crushed-astralite-ore-output', displayName: 'Crushed Astralite Ore Output', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-foresters-pot', displayName: 'Flawless Forester\'s Pot', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-gem', displayName: 'Flawless Gem', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-gem-encrusted-ring', displayName: 'Flawless Gem Encrusted Ring', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-gem-fragments', displayName: 'Flawless Gem Fragments', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-pebbles', displayName: 'Flawless Pebbles', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-pebbles-output', displayName: 'Flawless Pebbles Output', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-rock', displayName: 'Flawless Rock', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-stone-carvings', displayName: 'Flawless Stone Carvings', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-stone-research', displayName: 'Flawless Stone Research', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-unfired-foresters-pot', displayName: 'Flawless Unfired Forester\'s Pot', type: 'gatherable', tier: Tier.T10 },
];
