import { ItemNode, Tier } from '../item-node';

export const items: ItemNode[] = [
  { id: 'basic-wood-polish', displayName: 'Basic Wood Polish', type: 'gatherable', tier: Tier.T1 },
  { id: 'beginners-wood-research', displayName: 'Beginner\'s Wood Research', type: 'gatherable', tier: Tier.T1 },
  { id: 'grand-rough-sapphire', displayName: 'Grand Rough Sapphire', type: 'gatherable', tier: Tier.T1 },
  { id: 'massive-rough-sapphire', displayName: 'Massive Rough Sapphire', type: 'gatherable', tier: Tier.T1 },
  { id: 'potted-beech-sapling', displayName: 'Potted Beech Sapling', type: 'gatherable', tier: Tier.T1 },
  { id: 'potted-oak-sapling', displayName: 'Potted Oak Sapling', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-charcoal', displayName: 'Rough Charcoal', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-sapphire', displayName: 'Rough Sapphire', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-sapphire-fragment', displayName: 'Rough Sapphire Fragment', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-sapphire-ring', displayName: 'Rough Sapphire Ring', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-stripped-wood', displayName: 'Rough Stripped Wood', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-tree-bark', displayName: 'Rough Tree Bark', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-tree-bark-output', displayName: 'Rough Tree Bark Output', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-wood-log', displayName: 'Rough Wood Log', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-wood-log-output', displayName: 'Rough Wood Log Output', type: 'gatherable', tier: Tier.T1 },
  { id: 't1-bark-output', displayName: 'T1 Bark Output', type: 'gatherable', tier: Tier.T1 },
  { id: 'tiny-rough-sapphire', displayName: 'Tiny Rough Sapphire', type: 'gatherable', tier: Tier.T1 },
  { id: 'uncut-rough-sapphire', displayName: 'Uncut Rough Sapphire', type: 'gatherable', tier: Tier.T1 },
  { id: 'driftwood-crayfish', displayName: 'Driftwood Crayfish', type: 'gatherable', tier: Tier.T2 },
  { id: 'grand-simple-sapphire', displayName: 'Grand Simple Sapphire', type: 'gatherable', tier: Tier.T2 },
  { id: 'massive-simple-sapphire', displayName: 'Massive Simple Sapphire', type: 'gatherable', tier: Tier.T2 },
  { id: 'novices-wood-research', displayName: 'Novice\'s Wood Research', type: 'gatherable', tier: Tier.T2 },
  { id: 'potted-birch-sapling', displayName: 'Potted Birch Sapling', type: 'gatherable', tier: Tier.T2 },
  { id: 'potted-dendro-sapling', displayName: 'Potted Dendro Sapling', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-charcoal', displayName: 'Simple Charcoal', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-sapphire', displayName: 'Simple Sapphire', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-sapphire-fragment', displayName: 'Simple Sapphire Fragment', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-sapphire-ring', displayName: 'Simple Sapphire Ring', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-stripped-wood', displayName: 'Simple Stripped Wood', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-tree-bark', displayName: 'Simple Tree Bark', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-tree-bark-output', displayName: 'Simple Tree Bark Output', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-wood-log', displayName: 'Simple Wood Log', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-wood-log-output', displayName: 'Simple Wood Log Output', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-wood-polish', displayName: 'Simple Wood Polish', type: 'gatherable', tier: Tier.T2 },
  { id: 't2-bark-output', displayName: 'T2 Bark Output', type: 'gatherable', tier: Tier.T2 },
  { id: 't2-wood-logs-output', displayName: 'T2 Wood Logs Output', type: 'gatherable', tier: Tier.T2 },
  { id: 'tiny-simple-sapphire', displayName: 'Tiny Simple Sapphire', type: 'gatherable', tier: Tier.T2 },
  { id: 'uncut-simple-sapphire', displayName: 'Uncut Simple Sapphire', type: 'gatherable', tier: Tier.T2 },
  { id: 'essential-wood-research', displayName: 'Essential Wood Research', type: 'gatherable', tier: Tier.T3 },
  { id: 'grand-sturdy-sapphire', displayName: 'Grand Sturdy Sapphire', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-wood-polish', displayName: 'Infused Wood Polish', type: 'gatherable', tier: Tier.T3 },
  { id: 'massive-sturdy-sapphire', displayName: 'Massive Sturdy Sapphire', type: 'gatherable', tier: Tier.T3 },
  { id: 'potted-spruce-sapling', displayName: 'Potted Spruce Sapling', type: 'gatherable', tier: Tier.T3 },
  { id: 'potted-willow-sapling', displayName: 'Potted Willow Sapling', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-charcoal', displayName: 'Sturdy Charcoal', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-sapphire', displayName: 'Sturdy Sapphire', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-sapphire-fragment', displayName: 'Sturdy Sapphire Fragment', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-sapphire-ring', displayName: 'Sturdy Sapphire Ring', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-stripped-wood', displayName: 'Sturdy Stripped Wood', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-tree-bark', displayName: 'Sturdy Tree Bark', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-tree-bark-output', displayName: 'Sturdy Tree Bark Output', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-wood-log', displayName: 'Sturdy Wood Log', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-wood-log-output', displayName: 'Sturdy Wood Log Output', type: 'gatherable', tier: Tier.T3 },
  { id: 't3-bark-output', displayName: 'T3 Bark Output', type: 'gatherable', tier: Tier.T3 },
  { id: 't3-wood-logs-output', displayName: 'T3 Wood Logs Output', type: 'gatherable', tier: Tier.T3 },
  { id: 'tiny-sturdy-sapphire', displayName: 'Tiny Sturdy Sapphire', type: 'gatherable', tier: Tier.T3 },
  { id: 'uncut-sturdy-sapphire', displayName: 'Uncut Sturdy Sapphire', type: 'gatherable', tier: Tier.T3 },
  { id: 'fine-charcoal', displayName: 'Fine Charcoal', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-sapphire', displayName: 'Fine Sapphire', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-sapphire-fragment', displayName: 'Fine Sapphire Fragment', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-sapphire-ring', displayName: 'Fine Sapphire Ring', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-stripped-wood', displayName: 'Fine Stripped Wood', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-tree-bark', displayName: 'Fine Tree Bark', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-tree-bark-output', displayName: 'Fine Tree Bark Output', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-wood-log', displayName: 'Fine Wood Log', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-wood-log-output', displayName: 'Fine Wood Log Output', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-wood-polish', displayName: 'Fine Wood Polish', type: 'gatherable', tier: Tier.T4 },
  { id: 'grand-fine-sapphire', displayName: 'Grand Fine Sapphire', type: 'gatherable', tier: Tier.T4 },
  { id: 'massive-fine-sapphire', displayName: 'Massive Fine Sapphire', type: 'gatherable', tier: Tier.T4 },
  { id: 'potted-pine-sapling', displayName: 'Potted Pine Sapling', type: 'gatherable', tier: Tier.T4 },
  { id: 'proficient-wood-research', displayName: 'Proficient Wood Research', type: 'gatherable', tier: Tier.T4 },
  { id: 't4-bark-output', displayName: 'T4 Bark Output', type: 'gatherable', tier: Tier.T4 },
  { id: 't4-wood-logs-output', displayName: 'T4 Wood Logs Output', type: 'gatherable', tier: Tier.T4 },
  { id: 'tiny-fine-sapphire', displayName: 'Tiny Fine Sapphire', type: 'gatherable', tier: Tier.T4 },
  { id: 'uncut-fine-sapphire', displayName: 'Uncut Fine Sapphire', type: 'gatherable', tier: Tier.T4 },
  { id: 'advanced-wood-research', displayName: 'Advanced Wood Research', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-charcoal', displayName: 'Exquisite Charcoal', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-sapphire', displayName: 'Exquisite Sapphire', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-sapphire-fragment', displayName: 'Exquisite Sapphire Fragment', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-sapphire-ring', displayName: 'Exquisite Sapphire Ring', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-stripped-wood', displayName: 'Exquisite Stripped Wood', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-tree-bark', displayName: 'Exquisite Tree Bark', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-tree-bark-output', displayName: 'Exquisite Tree Bark Output', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-wood-log', displayName: 'Exquisite Wood Log', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-wood-log-output', displayName: 'Exquisite Wood Log Output', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-wood-polish', displayName: 'Exquisite Wood Polish', type: 'gatherable', tier: Tier.T5 },
  { id: 'grand-exquisite-sapphire', displayName: 'Grand Exquisite Sapphire', type: 'gatherable', tier: Tier.T5 },
  { id: 'massive-exquisite-sapphire', displayName: 'Massive Exquisite Sapphire', type: 'gatherable', tier: Tier.T5 },
  { id: 'potted-cypress-sapling', displayName: 'Potted Cypress Sapling', type: 'gatherable', tier: Tier.T5 },
  { id: 't5-bark-output', displayName: 'T5 Bark Output', type: 'gatherable', tier: Tier.T5 },
  { id: 't5-wood-logs-output', displayName: 'T5 Wood Logs Output', type: 'gatherable', tier: Tier.T5 },
  { id: 'tiny-exquisite-sapphire', displayName: 'Tiny Exquisite Sapphire', type: 'gatherable', tier: Tier.T5 },
  { id: 'uncut-exquisite-sapphire', displayName: 'Uncut Exquisite Sapphire', type: 'gatherable', tier: Tier.T5 },
  { id: 'comprehensive-wood-research', displayName: 'Comprehensive Wood Research', type: 'gatherable', tier: Tier.T6 },
  { id: 'grand-peerless-sapphire', displayName: 'Grand Peerless Sapphire', type: 'gatherable', tier: Tier.T6 },
  { id: 'massive-peerless-sapphire', displayName: 'Massive Peerless Sapphire', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-charcoal', displayName: 'Peerless Charcoal', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-sapphire', displayName: 'Peerless Sapphire', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-sapphire-fragment', displayName: 'Peerless Sapphire Fragment', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-sapphire-ring', displayName: 'Peerless Sapphire Ring', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-stripped-wood', displayName: 'Peerless Stripped Wood', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-tree-bark', displayName: 'Peerless Tree Bark', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-tree-bark-output', displayName: 'Peerless Tree Bark Output', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-wood-log', displayName: 'Peerless Wood Log', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-wood-log-output', displayName: 'Peerless Wood Log Output', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-wood-polish', displayName: 'Peerless Wood Polish', type: 'gatherable', tier: Tier.T6 },
  { id: 'potted-maple-sapling', displayName: 'Potted Maple Sapling', type: 'gatherable', tier: Tier.T6 },
  { id: 't6-bark-output', displayName: 'T6 Bark Output', type: 'gatherable', tier: Tier.T6 },
  { id: 't6-wood-logs-output', displayName: 'T6 Wood Logs Output', type: 'gatherable', tier: Tier.T6 },
  { id: 'tiny-peerless-sapphire', displayName: 'Tiny Peerless Sapphire', type: 'gatherable', tier: Tier.T6 },
  { id: 'uncut-peerless-sapphire', displayName: 'Uncut Peerless Sapphire', type: 'gatherable', tier: Tier.T6 },
  { id: 'ornate-charcoal', displayName: 'Ornate Charcoal', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-sapphire', displayName: 'Ornate Sapphire', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-sapphire-fragment', displayName: 'Ornate Sapphire Fragment', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-sapphire-ring', displayName: 'Ornate Sapphire Ring', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-stripped-wood', displayName: 'Ornate Stripped Wood', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-tree-bark', displayName: 'Ornate Tree Bark', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-tree-bark-output', displayName: 'Ornate Tree Bark Output', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-wood-log', displayName: 'Ornate Wood Log', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-wood-log-output', displayName: 'Ornate Wood Log Output', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-wood-polish', displayName: 'Ornate Wood Polish', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-wood-research', displayName: 'Ornate Wood Research', type: 'gatherable', tier: Tier.T7 },
  { id: 't7-bark-output', displayName: 'T7 Bark Output', type: 'gatherable', tier: Tier.T7 },
  { id: 'uncut-ornate-sapphire', displayName: 'Uncut Ornate Sapphire', type: 'gatherable', tier: Tier.T7 },
  { id: 'pristine-charcoal', displayName: 'Pristine Charcoal', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-sapphire', displayName: 'Pristine Sapphire', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-sapphire-fragment', displayName: 'Pristine Sapphire Fragment', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-sapphire-ring', displayName: 'Pristine Sapphire Ring', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-stripped-wood', displayName: 'Pristine Stripped Wood', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-tree-bark', displayName: 'Pristine Tree Bark', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-tree-bark-output', displayName: 'Pristine Tree Bark Output', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-wood-log', displayName: 'Pristine Wood Log', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-wood-log-output', displayName: 'Pristine Wood Log Output', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-wood-polish', displayName: 'Pristine Wood Polish', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-wood-research', displayName: 'Pristine Wood Research', type: 'gatherable', tier: Tier.T8 },
  { id: 't8-bark-output', displayName: 'T8 Bark Output', type: 'gatherable', tier: Tier.T8 },
  { id: 'uncut-pristine-sapphire', displayName: 'Uncut Pristine Sapphire', type: 'gatherable', tier: Tier.T8 },
  { id: 'magnificient-charcoal', displayName: 'Magnificient Charcoal', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-sapphire', displayName: 'Magnificient Sapphire', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-sapphire-fragment', displayName: 'Magnificient Sapphire Fragment', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-sapphire-ring', displayName: 'Magnificient Sapphire Ring', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-stripped-wood', displayName: 'Magnificient Stripped Wood', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-tree-bark', displayName: 'Magnificient Tree Bark', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-tree-bark-output', displayName: 'Magnificient Tree Bark Output', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-wood-log', displayName: 'Magnificient Wood Log', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-wood-log-output', displayName: 'Magnificient Wood Log Output', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-wood-polish', displayName: 'Magnificient Wood Polish', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-wood-research', displayName: 'Magnificient Wood Research', type: 'gatherable', tier: Tier.T9 },
  { id: 't9-bark-output', displayName: 'T9 Bark Output', type: 'gatherable', tier: Tier.T9 },
  { id: 'uncut-magnificient-sapphire', displayName: 'Uncut Magnificient Sapphire', type: 'gatherable', tier: Tier.T9 },
  { id: 'flawless-charcoal', displayName: 'Flawless Charcoal', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-sapphire', displayName: 'Flawless Sapphire', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-sapphire-fragment', displayName: 'Flawless Sapphire Fragment', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-sapphire-ring', displayName: 'Flawless Sapphire Ring', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-stripped-wood', displayName: 'Flawless Stripped Wood', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-tree-bark', displayName: 'Flawless Tree Bark', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-tree-bark-output', displayName: 'Flawless Tree Bark Output', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-wood-log', displayName: 'Flawless Wood Log', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-wood-log-output', displayName: 'Flawless Wood Log Output', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-wood-polish', displayName: 'Flawless Wood Polish', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-wood-research', displayName: 'Flawless Wood Research', type: 'gatherable', tier: Tier.T10 },
  { id: 't10-bark-output', displayName: 'T10 Bark Output', type: 'gatherable', tier: Tier.T10 },
  { id: 'uncut-flawless-sapphire', displayName: 'Uncut Flawless Sapphire', type: 'gatherable', tier: Tier.T10 },
];
