import { ItemNode, Tier } from '../item-node';

export const items: ItemNode[] = [
  { id: 'basic-embergrain', displayName: 'Basic Embergrain', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-embergrain-dough', displayName: 'Basic Embergrain Dough', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-embergrain-experiment', displayName: 'Basic Embergrain Experiment', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-embergrain-flour', displayName: 'Basic Embergrain Flour', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-embergrain-plant', displayName: 'Basic Embergrain Plant', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-embergrain-products', displayName: 'Basic Embergrain Products', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-embergrain-seeds', displayName: 'Basic Embergrain Seeds', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-flower', displayName: 'Basic Flower', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-mushroom', displayName: 'Basic Mushroom', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-mushroom-experiment', displayName: 'Basic Mushroom Experiment', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-starbulb', displayName: 'Basic Starbulb', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-starbulb-experiment', displayName: 'Basic Starbulb Experiment', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-starbulb-plant', displayName: 'Basic Starbulb Plant', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-starbulb-products', displayName: 'Basic Starbulb Products', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-starbulb-seeds', displayName: 'Basic Starbulb Seeds', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-wispweave-plant', displayName: 'Basic Wispweave Plant', type: 'gatherable', tier: Tier.T1 },
  { id: 'basic-wispweave-seeds', displayName: 'Basic Wispweave Seeds', type: 'gatherable', tier: Tier.T1 },
  { id: 'beech-seed', displayName: 'Beech Seed', type: 'gatherable', tier: Tier.T1 },
  { id: 'dried-basic-flowers', displayName: 'Dried Basic Flowers', type: 'gatherable', tier: Tier.T1 },
  { id: 'oak-seed', displayName: 'Oak Seed', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-bulb-rolls', displayName: 'Plain Bulb Rolls', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-deluxe-bulb-rolls', displayName: 'Plain Deluxe Bulb Rolls', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-deluxe-fish-and-bulbs', displayName: 'Plain Deluxe Fish and Bulbs', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-deluxe-ground-meat-and-mashed-bulbs', displayName: 'Plain Deluxe Ground Meat and Mashed Bulbs', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-deluxe-mushroom-stuffed-bulbs', displayName: 'Plain Deluxe Mushroom Stuffed Bulbs', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-fish-and-bulbs', displayName: 'Plain Fish and Bulbs', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-ground-meat-and-mashed-bulbs', displayName: 'Plain Ground Meat and Mashed Bulbs', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-mashed-bulbs', displayName: 'Plain Mashed Bulbs', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-mashed-bulbs-output', displayName: 'Plain Mashed Bulbs Output', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-mushroom-skewer', displayName: 'Plain Mushroom Skewer', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-mushroom-stuffed-bulbs', displayName: 'Plain Mushroom Stuffed Bulbs', type: 'gatherable', tier: Tier.T1 },
  { id: 'plain-raw-bulb-rolls', displayName: 'Plain Raw Bulb Rolls', type: 'gatherable', tier: Tier.T1 },
  { id: 'rough-plant-fiber', displayName: 'Rough Plant Fiber', type: 'gatherable', tier: Tier.T1 },
  { id: 'wild-fiberplant-seeds', displayName: 'Wild Fiberplant Seeds', type: 'gatherable', tier: Tier.T1 },
  { id: 'wild-grain', displayName: 'Wild Grain', type: 'gatherable', tier: Tier.T1 },
  { id: 'wild-grain-seeds', displayName: 'Wild Grain Seeds', type: 'gatherable', tier: Tier.T1 },
  { id: 'wild-vegetable', displayName: 'Wild Vegetable', type: 'gatherable', tier: Tier.T1 },
  { id: 'wild-vegetable-seeds', displayName: 'Wild Vegetable Seeds', type: 'gatherable', tier: Tier.T1 },
  { id: 'birch-seed', displayName: 'Birch Seed', type: 'gatherable', tier: Tier.T2 },
  { id: 'dendro-seed', displayName: 'Dendro Seed', type: 'gatherable', tier: Tier.T2 },
  { id: 'dried-simple-flowers', displayName: 'Dried Simple Flowers', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-bulb-rolls', displayName: 'Savory Bulb Rolls', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-deluxe-bulb-rolls', displayName: 'Savory Deluxe Bulb Rolls', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-deluxe-fish-and-bulbs', displayName: 'Savory Deluxe Fish and Bulbs', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-deluxe-ground-meat-and-mashed-bulbs', displayName: 'Savory Deluxe Ground Meat and Mashed Bulbs', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-deluxe-mushroom-stuffed-bulbs', displayName: 'Savory Deluxe Mushroom Stuffed Bulbs', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-fish-and-bulbs', displayName: 'Savory Fish and Bulbs', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-ground-meat-and-mashed-bulbs', displayName: 'Savory Ground Meat and Mashed Bulbs', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-mashed-bulbs', displayName: 'Savory Mashed Bulbs', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-mashed-bulbs-output', displayName: 'Savory Mashed Bulbs Output', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-mushroom-skewer', displayName: 'Savory Mushroom Skewer', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-mushroom-stuffed-bulbs', displayName: 'Savory Mushroom Stuffed Bulbs', type: 'gatherable', tier: Tier.T2 },
  { id: 'savory-raw-bulb-rolls', displayName: 'Savory Raw Bulb Rolls', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-embergrain', displayName: 'Simple Embergrain', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-embergrain-dough', displayName: 'Simple Embergrain Dough', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-embergrain-experiment', displayName: 'Simple Embergrain Experiment', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-embergrain-flour', displayName: 'Simple Embergrain Flour', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-embergrain-plant', displayName: 'Simple Embergrain Plant', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-embergrain-products', displayName: 'Simple Embergrain Products', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-embergrain-seeds', displayName: 'Simple Embergrain Seeds', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-flower', displayName: 'Simple Flower', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-mushroom', displayName: 'Simple Mushroom', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-mushroom-experiment', displayName: 'Simple Mushroom Experiment', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-plant-fiber', displayName: 'Simple Plant Fiber', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-starbulb', displayName: 'Simple Starbulb', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-starbulb-experiment', displayName: 'Simple Starbulb Experiment', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-starbulb-plant', displayName: 'Simple Starbulb Plant', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-starbulb-products', displayName: 'Simple Starbulb Products', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-starbulb-seeds', displayName: 'Simple Starbulb Seeds', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-wispweave-plant', displayName: 'Simple Wispweave Plant', type: 'gatherable', tier: Tier.T2 },
  { id: 'simple-wispweave-seeds', displayName: 'Simple Wispweave Seeds', type: 'gatherable', tier: Tier.T2 },
  { id: 't2-fiber-output', displayName: 'T2 Fiber Output', type: 'gatherable', tier: Tier.T2 },
  { id: 't2-flower-output', displayName: 'T2 Flower Output', type: 'gatherable', tier: Tier.T2 },
  { id: 'dried-infused-flowers', displayName: 'Dried Infused Flowers', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-embergrain', displayName: 'Infused Embergrain', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-embergrain-dough', displayName: 'Infused Embergrain Dough', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-embergrain-experiment', displayName: 'Infused Embergrain Experiment', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-embergrain-flour', displayName: 'Infused Embergrain Flour', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-embergrain-plant', displayName: 'Infused Embergrain Plant', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-embergrain-products', displayName: 'Infused Embergrain Products', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-embergrain-seeds', displayName: 'Infused Embergrain Seeds', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-flower', displayName: 'Infused Flower', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-mushroom', displayName: 'Infused Mushroom', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-mushroom-experiment', displayName: 'Infused Mushroom Experiment', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-starbulb', displayName: 'Infused Starbulb', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-starbulb-experiment', displayName: 'Infused Starbulb Experiment', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-starbulb-plant', displayName: 'Infused Starbulb Plant', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-starbulb-products', displayName: 'Infused Starbulb Products', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-starbulb-seeds', displayName: 'Infused Starbulb Seeds', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-wispweave-plant', displayName: 'Infused Wispweave Plant', type: 'gatherable', tier: Tier.T3 },
  { id: 'infused-wispweave-seeds', displayName: 'Infused Wispweave Seeds', type: 'gatherable', tier: Tier.T3 },
  { id: 'spruce-seed', displayName: 'Spruce Seed', type: 'gatherable', tier: Tier.T3 },
  { id: 'sturdy-plant-fiber', displayName: 'Sturdy Plant Fiber', type: 'gatherable', tier: Tier.T3 },
  { id: 't3-fiber-output', displayName: 'T3 Fiber Output', type: 'gatherable', tier: Tier.T3 },
  { id: 't3-flower-output', displayName: 'T3 Flower Output', type: 'gatherable', tier: Tier.T3 },
  { id: 'willow-seed', displayName: 'Willow Seed', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-bulb-rolls', displayName: 'Zesty Bulb Rolls', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-deluxe-bulb-rolls', displayName: 'Zesty Deluxe Bulb Rolls', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-deluxe-fish-and-bulbs', displayName: 'Zesty Deluxe Fish and Bulbs', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-deluxe-ground-meat-and-mashed-bulbs', displayName: 'Zesty Deluxe Ground Meat and Mashed Bulbs', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-deluxe-mushroom-stuffed-bulbs', displayName: 'Zesty Deluxe Mushroom Stuffed Bulbs', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-fish-and-bulbs', displayName: 'Zesty Fish and Bulbs', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-ground-meat-and-mashed-bulbs', displayName: 'Zesty Ground Meat and Mashed Bulbs', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-mashed-bulbs', displayName: 'Zesty Mashed Bulbs', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-mashed-bulbs-output', displayName: 'Zesty Mashed Bulbs Output', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-mushroom-skewer', displayName: 'Zesty Mushroom Skewer', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-mushroom-stuffed-bulbs', displayName: 'Zesty Mushroom Stuffed Bulbs', type: 'gatherable', tier: Tier.T3 },
  { id: 'zesty-raw-bulb-rolls', displayName: 'Zesty Raw Bulb Rolls', type: 'gatherable', tier: Tier.T3 },
  { id: 'dried-fine-flowers', displayName: 'Dried Fine Flowers', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-bulb-rolls', displayName: 'Fine Bulb Rolls', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-deluxe-bulb-rolls', displayName: 'Fine Deluxe Bulb Rolls', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-deluxe-fish-and-bulbs', displayName: 'Fine Deluxe Fish and Bulbs', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-deluxe-ground-meat-and-mashed-bulbs', displayName: 'Fine Deluxe Ground Meat and Mashed Bulbs', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-deluxe-mushroom-stuffed-bulbs', displayName: 'Fine Deluxe Mushroom Stuffed Bulbs', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-embergrain', displayName: 'Fine Embergrain', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-embergrain-dough', displayName: 'Fine Embergrain Dough', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-embergrain-experiment', displayName: 'Fine Embergrain Experiment', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-embergrain-flour', displayName: 'Fine Embergrain Flour', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-embergrain-plant', displayName: 'Fine Embergrain Plant', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-embergrain-products', displayName: 'Fine Embergrain Products', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-embergrain-seeds', displayName: 'Fine Embergrain Seeds', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-fish-and-bulbs', displayName: 'Fine Fish and Bulbs', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-flower', displayName: 'Fine Flower', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-ground-meat-and-mashed-bulbs', displayName: 'Fine Ground Meat and Mashed Bulbs', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-mashed-bulbs', displayName: 'Fine Mashed Bulbs', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-mashed-bulbs-output', displayName: 'Fine Mashed Bulbs Output', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-mushroom', displayName: 'Fine Mushroom', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-mushroom-experiment', displayName: 'Fine Mushroom Experiment', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-mushroom-skewer', displayName: 'Fine Mushroom Skewer', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-mushroom-stuffed-bulbs', displayName: 'Fine Mushroom Stuffed Bulbs', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-plant-fiber', displayName: 'Fine Plant Fiber', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-raw-bulb-rolls', displayName: 'Fine Raw Bulb Rolls', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-starbulb', displayName: 'Fine Starbulb', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-starbulb-experiment', displayName: 'Fine Starbulb Experiment', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-starbulb-plant', displayName: 'Fine Starbulb Plant', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-starbulb-products', displayName: 'Fine Starbulb Products', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-starbulb-seeds', displayName: 'Fine Starbulb Seeds', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-wispweave-plant', displayName: 'Fine Wispweave Plant', type: 'gatherable', tier: Tier.T4 },
  { id: 'fine-wispweave-seeds', displayName: 'Fine Wispweave Seeds', type: 'gatherable', tier: Tier.T4 },
  { id: 'pine-seed', displayName: 'Pine Seed', type: 'gatherable', tier: Tier.T4 },
  { id: 't4-fiber-output', displayName: 'T4 Fiber Output', type: 'gatherable', tier: Tier.T4 },
  { id: 't4-flower-output', displayName: 'T4 Flower Output', type: 'gatherable', tier: Tier.T4 },
  { id: 'cypress-seed', displayName: 'Cypress Seed', type: 'gatherable', tier: Tier.T5 },
  { id: 'dried-exquisite-flowers', displayName: 'Dried Exquisite Flowers', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-embergrain', displayName: 'Exquisite Embergrain', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-embergrain-dough', displayName: 'Exquisite Embergrain Dough', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-embergrain-experiment', displayName: 'Exquisite Embergrain Experiment', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-embergrain-flour', displayName: 'Exquisite Embergrain Flour', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-embergrain-plant', displayName: 'Exquisite Embergrain Plant', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-embergrain-products', displayName: 'Exquisite Embergrain Products', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-embergrain-seeds', displayName: 'Exquisite Embergrain Seeds', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-flower', displayName: 'Exquisite Flower', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-mushroom', displayName: 'Exquisite Mushroom', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-mushroom-experiment', displayName: 'Exquisite Mushroom Experiment', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-plant-fiber', displayName: 'Exquisite Plant Fiber', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-starbulb', displayName: 'Exquisite Starbulb', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-starbulb-experiment', displayName: 'Exquisite Starbulb Experiment', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-starbulb-plant', displayName: 'Exquisite Starbulb Plant', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-starbulb-products', displayName: 'Exquisite Starbulb Products', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-starbulb-seeds', displayName: 'Exquisite Starbulb Seeds', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-wispweave-plant', displayName: 'Exquisite Wispweave Plant', type: 'gatherable', tier: Tier.T5 },
  { id: 'exquisite-wispweave-seeds', displayName: 'Exquisite Wispweave Seeds', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-bulb-rolls', displayName: 'Succulent Bulb Rolls', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-deluxe-bulb-rolls', displayName: 'Succulent Deluxe Bulb Rolls', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-deluxe-fish-and-bulbs', displayName: 'Succulent Deluxe Fish and Bulbs', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-deluxe-ground-meat-and-mashed-bulbs', displayName: 'Succulent Deluxe Ground Meat and Mashed Bulbs', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-deluxe-mushroom-stuffed-bulbs', displayName: 'Succulent Deluxe Mushroom Stuffed Bulbs', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-fish-and-bulbs', displayName: 'Succulent Fish and Bulbs', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-ground-meat-and-mashed-bulbs', displayName: 'Succulent Ground Meat and Mashed Bulbs', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-mashed-bulbs', displayName: 'Succulent Mashed Bulbs', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-mashed-bulbs-output', displayName: 'Succulent Mashed Bulbs Output', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-mushroom-skewer', displayName: 'Succulent Mushroom Skewer', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-mushroom-stuffed-bulbs', displayName: 'Succulent Mushroom Stuffed Bulbs', type: 'gatherable', tier: Tier.T5 },
  { id: 'succulent-raw-bulb-rolls', displayName: 'Succulent Raw Bulb Rolls', type: 'gatherable', tier: Tier.T5 },
  { id: 't5-fiber-output', displayName: 'T5 Fiber Output', type: 'gatherable', tier: Tier.T5 },
  { id: 't5-flower-output', displayName: 'T5 Flower Output', type: 'gatherable', tier: Tier.T5 },
  { id: 'ambriosal-mashed-bulbs-output', displayName: 'Ambriosal Mashed Bulbs Output', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-bulb-rolls', displayName: 'Ambrosial Bulb Rolls', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-deluxe-bulb-rolls', displayName: 'Ambrosial Deluxe Bulb Rolls', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-deluxe-fish-and-bulbs', displayName: 'Ambrosial Deluxe Fish and Bulbs', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-deluxe-ground-meat-and-mashed-bulbs', displayName: 'Ambrosial Deluxe Ground Meat and Mashed Bulbs', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-deluxe-mushroom-stuffed-bulbs', displayName: 'Ambrosial Deluxe Mushroom Stuffed Bulbs', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-fish-and-bulbs', displayName: 'Ambrosial Fish and Bulbs', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-ground-meat-and-mashed-bulbs', displayName: 'Ambrosial Ground Meat and Mashed Bulbs', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-mashed-bulbs', displayName: 'Ambrosial Mashed Bulbs', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-mashed-bulbs-output', displayName: 'Ambrosial Mashed Bulbs Output', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-mushroom-skewer', displayName: 'Ambrosial Mushroom Skewer', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-mushroom-stuffed-bulbs', displayName: 'Ambrosial Mushroom Stuffed Bulbs', type: 'gatherable', tier: Tier.T6 },
  { id: 'ambrosial-raw-bulb-rolls', displayName: 'Ambrosial Raw Bulb Rolls', type: 'gatherable', tier: Tier.T6 },
  { id: 'dried-peerless-flowers', displayName: 'Dried Peerless Flowers', type: 'gatherable', tier: Tier.T6 },
  { id: 'maple-seed', displayName: 'Maple Seed', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-embergrain', displayName: 'Peerless Embergrain', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-embergrain-dough', displayName: 'Peerless Embergrain Dough', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-embergrain-experiment', displayName: 'Peerless Embergrain Experiment', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-embergrain-flour', displayName: 'Peerless Embergrain Flour', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-embergrain-plant', displayName: 'Peerless Embergrain Plant', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-embergrain-products', displayName: 'Peerless Embergrain Products', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-embergrain-seeds', displayName: 'Peerless Embergrain Seeds', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-flower', displayName: 'Peerless Flower', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-mushroom', displayName: 'Peerless Mushroom', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-mushroom-experiment', displayName: 'Peerless Mushroom Experiment', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-plant-fiber', displayName: 'Peerless Plant Fiber', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-starbulb', displayName: 'Peerless Starbulb', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-starbulb-experiment', displayName: 'Peerless Starbulb Experiment', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-starbulb-plant', displayName: 'Peerless Starbulb Plant', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-starbulb-products', displayName: 'Peerless Starbulb Products', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-starbulb-seeds', displayName: 'Peerless Starbulb Seeds', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-wispweave-plant', displayName: 'Peerless Wispweave Plant', type: 'gatherable', tier: Tier.T6 },
  { id: 'peerless-wispweave-seeds', displayName: 'Peerless Wispweave Seeds', type: 'gatherable', tier: Tier.T6 },
  { id: 't6-fiber-output', displayName: 'T6 Fiber Output', type: 'gatherable', tier: Tier.T6 },
  { id: 't6-flower-output', displayName: 'T6 Flower Output', type: 'gatherable', tier: Tier.T6 },
  { id: 'flavorful-ground-meat-and-mashed-bulbs', displayName: 'Flavorful Ground Meat and Mashed Bulbs', type: 'gatherable', tier: Tier.T7 },
  { id: 'flavorful-mashed-bulbs', displayName: 'Flavorful Mashed Bulbs', type: 'gatherable', tier: Tier.T7 },
  { id: 'flavorful-mashed-bulbs-output', displayName: 'Flavorful Mashed Bulbs Output', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-embergrain', displayName: 'Ornate Embergrain', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-embergrain-dough', displayName: 'Ornate Embergrain Dough', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-embergrain-flour', displayName: 'Ornate Embergrain Flour', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-embergrain-plant', displayName: 'Ornate Embergrain Plant', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-embergrain-products', displayName: 'Ornate Embergrain Products', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-embergrain-seeds', displayName: 'Ornate Embergrain Seeds', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-flower', displayName: 'Ornate Flower', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-mushroom', displayName: 'Ornate Mushroom', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-plant-fiber', displayName: 'Ornate Plant Fiber', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-starbulb', displayName: 'Ornate Starbulb', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-starbulb-plant', displayName: 'Ornate Starbulb Plant', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-starbulb-products', displayName: 'Ornate Starbulb Products', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-starbulb-seeds', displayName: 'Ornate Starbulb Seeds', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-wispweave-plant', displayName: 'Ornate Wispweave Plant', type: 'gatherable', tier: Tier.T7 },
  { id: 'ornate-wispweave-seeds', displayName: 'Ornate Wispweave Seeds', type: 'gatherable', tier: Tier.T7 },
  { id: 't7-fiber-output', displayName: 'T7 Fiber Output', type: 'gatherable', tier: Tier.T7 },
  { id: 't7-flower-output', displayName: 'T7 Flower Output', type: 'gatherable', tier: Tier.T7 },
  { id: 'delicious-mashed-bulbs', displayName: 'Delicious Mashed Bulbs', type: 'gatherable', tier: Tier.T8 },
  { id: 'delicious-mashed-bulbs-output', displayName: 'Delicious Mashed Bulbs Output', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-embergrain', displayName: 'Pristine Embergrain', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-embergrain-dough', displayName: 'Pristine Embergrain Dough', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-embergrain-flour', displayName: 'Pristine Embergrain Flour', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-embergrain-plant', displayName: 'Pristine Embergrain Plant', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-embergrain-products', displayName: 'Pristine Embergrain Products', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-embergrain-seeds', displayName: 'Pristine Embergrain Seeds', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-flower', displayName: 'Pristine Flower', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-mushroom', displayName: 'Pristine Mushroom', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-plant-fiber', displayName: 'Pristine Plant Fiber', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-starbulb', displayName: 'Pristine Starbulb', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-starbulb-plant', displayName: 'Pristine Starbulb Plant', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-starbulb-products', displayName: 'Pristine Starbulb Products', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-starbulb-seeds', displayName: 'Pristine Starbulb Seeds', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-wispweave-plant', displayName: 'Pristine Wispweave Plant', type: 'gatherable', tier: Tier.T8 },
  { id: 'pristine-wispweave-seeds', displayName: 'Pristine Wispweave Seeds', type: 'gatherable', tier: Tier.T8 },
  { id: 't8-fiber-output', displayName: 'T8 Fiber Output', type: 'gatherable', tier: Tier.T8 },
  { id: 't8-flower-output', displayName: 'T8 Flower Output', type: 'gatherable', tier: Tier.T8 },
  { id: 'magnificient-embergrain', displayName: 'Magnificient Embergrain', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-embergrain-dough', displayName: 'Magnificient Embergrain Dough', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-embergrain-flour', displayName: 'Magnificient Embergrain Flour', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-embergrain-plant', displayName: 'Magnificient Embergrain Plant', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-embergrain-products', displayName: 'Magnificient Embergrain Products', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-embergrain-seeds', displayName: 'Magnificient Embergrain Seeds', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-flower', displayName: 'Magnificient Flower', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-mushroom', displayName: 'Magnificient Mushroom', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-plant-fiber', displayName: 'Magnificient Plant Fiber', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-starbulb', displayName: 'Magnificient Starbulb', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-starbulb-plant', displayName: 'Magnificient Starbulb Plant', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-starbulb-products', displayName: 'Magnificient Starbulb Products', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-starbulb-seeds', displayName: 'Magnificient Starbulb Seeds', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-wispweave-plant', displayName: 'Magnificient Wispweave Plant', type: 'gatherable', tier: Tier.T9 },
  { id: 'magnificient-wispweave-seeds', displayName: 'Magnificient Wispweave Seeds', type: 'gatherable', tier: Tier.T9 },
  { id: 'flawless-embergrain', displayName: 'Flawless Embergrain', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-embergrain-dough', displayName: 'Flawless Embergrain Dough', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-embergrain-flour', displayName: 'Flawless Embergrain Flour', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-embergrain-plant', displayName: 'Flawless Embergrain Plant', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-embergrain-products', displayName: 'Flawless Embergrain Products', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-embergrain-seeds', displayName: 'Flawless Embergrain Seeds', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-flower', displayName: 'Flawless Flower', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-mushroom', displayName: 'Flawless Mushroom', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-plant-fiber', displayName: 'Flawless Plant Fiber', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-starbulb', displayName: 'Flawless Starbulb', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-starbulb-plant', displayName: 'Flawless Starbulb Plant', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-starbulb-products', displayName: 'Flawless Starbulb Products', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-starbulb-seeds', displayName: 'Flawless Starbulb Seeds', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-wispweave-plant', displayName: 'Flawless Wispweave Plant', type: 'gatherable', tier: Tier.T10 },
  { id: 'flawless-wispweave-seeds', displayName: 'Flawless Wispweave Seeds', type: 'gatherable', tier: Tier.T10 },
];
